### ISSUE TITLE
Switching between tab groups using keyboard doesn't work

### ISSUE THREAD

**Issue by mtjensen** [Quicksaver/Tab-Groups#356] opened 2016-06-27 16:55 UTC
In the tab groups overview mode "Single View", using the keyboard to switch between tab groups doesn't seem to work properly. Tab and the arrow keys work correctly to navigate between open tabs in the current group. However, pressing the up arrow key to focus on the tab group pane causes:

1. on the first keypress, the first tab group is focused 
2. on the second "up" keypress focuses the second tab group 
3. subsequent "up" keypresses toggle between tab group one and two

- While the tab group pane is focused, focus also remains on the first tab of the selected group. Pressing any other arrow key than "up" will move within the group as normal.

I would expect instead the behaviour that the tab group previews in the group pane function exactly like the tab previews, and that navigating between them and the tab previews with the arrow keys is seamless. I would expect tab key navigation to be bounded to the current pane (tab groups or tabs).

Thanks a lot.

**Comment by Quicksaver** [comment] 2016-06-27 16:59
That's not supposed to happen at all actually, arrow keys should switch between groups while in single view. You should be able to use the customizable keyboard shortcuts (in the add-on preferences) to do that. I'll have to fix that.

**Comment by mtjensen** [comment] 2016-06-27 17:09
Sorry, I don't think I explained it correctly. This screenshot shows the view in which the behaviour occurs.
![screenshot 2016-06-27 19 03 00](https://cloud.githubusercontent.com/assets/10678767/16388714/9b19e484-3c9a-11e6-9881-e5600ce48089.png). Section 1 is what I call the tab groups pane, section 2 is the tabs pane. Thanks for the quick reply :)

**Comment by Quicksaver** [comment] 2016-06-27 17:11
I did understand what you mean. ;)

**Comment by mtjensen** [comment] 2016-06-27 17:13
Okay. I do understand that there are shortcuts to switch tab groups, but I have a single key shortcut to trigger the tab group overview, and it would be great to be able to switch easily between tab groups within that view just by using the arrow keys.

Thanks again for looking into it!

**Comment by Noexpert** [comment] 2016-07-03 13:01
Duplicate of #323

**Comment by Quicksaver** [comment] 2016-10-14 23:27
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) has some fixes for tab navigation while in single view (it should no longer jump "randomly" to another group). Also, use Ctrl+Tab and Ctrl+Shift+Tab to navigate between groups. Please give it a try and let me know how it works for you.

**Closed by Quicksaver** 2016-10-14 23:27 UTC
Labels: bug, important

**Comment by mtjensen** [comment] 2016-10-16 16:31
Hi, thanks for the update. I just tried it and the shortcuts to switch
tabgroups work, which is great.

However in single view I now cannot move the focus to the top bar of tab
groups at all. Effectively the behaviour seems to be even more limited, is
this intentional?

Mike

2016-10-15 1:27 GMT+02:00 Luís Miguel <notifications@github.com>:

**Comment by Quicksaver** [comment] 2016-10-16 16:34
Yeah, you were never meant to be able to "focus" the top group thumbnails like that, it was just by chance that it "kinda worked" before. As I mentioned, use Ctrl+Tab and Ctrl+Shift+Tab to switch between groups; the arrow keys will just switch between tabs.

**Comment by jmain33** [comment] 2016-10-17 11:26
## +1 
* Navigation using [Tab] [Shift–Tab] [Ctrl–Tab] [Ctrl–Shift–Tab] all work in a conventional and anticipated manner, regardless of which of the 3 layouts is chosen.

## -1 
* Using arrow keys in any layout is wacky and unpredictable, most especially in the 2 multi-group views. In single view there should be wrapping at the 4 edges [up—down—left—right] in the case of thumbnails or icons.

**To avoid the hassle you may want consider completely scrapping the usage of arrow keys and provide further clarity, for users, to usage of the [TAB] key.**
^ Due to the fact that precisely how the arrows should work within and between groups across several layouts can be tricky to figure out.

**Comment by Quicksaver** [comment] 2016-10-17 12:01
> Using arrow keys in any layout is wacky and unpredictable, most especially in the 2 multi-group views.

Pressing an arrow key is supposed to take you to the closest tab in that direction, regardless of what group it's in. Although that could make use of some improvement...

> To avoid the hassle you may want consider completely scrapping the usage of arrow keys

That has always been the behavior ever since it was a built-in feature in Firefox. Removing it would cause even more hassle to those users that have gotten used to it and rely on it. I would rather improve that behavior where I can rather than scrape it completely.

**Comment by mtjensen** [comment] 2016-10-18 08:28
Okay. Would make a great feature for a future update if you ever felt keen!

Thanks again!

2016-10-16 18:34 GMT+02:00 Luís Miguel <notifications@github.com>:

**Comment by jmain33** [comment] 2016-10-19 11:16
The emphasized portion -below- is the issue.
> Pressing an arrow key is supposed to take you to the closest tab in that direction, ***regardless of what group it's in***. Although that could make use of some improvement...

It certainly could use some improvement!! When using the arrow keys in free arrange or the grid layout the focus shifts toward any direction, over any distance and sometimes not at all (You can be at the mid-section of a group press [down-arrow] and it will jump up to the mid-section of a group above).

I believe they should function similarly to [tab] & [shift+tab], with the exception that they switch groups when the internal boundary of a group is reached, if you so desire.
