### ISSUE TITLE
Jumps to another group after a tab was closed

### ISSUE THREAD

**Issue by IzziRoller** [Quicksaver/Tab-Groups#58] opened 2016-01-16 21:58 UTC
Many times when I close current tab, it goes to a tab from another group. And I have to switch back to initial group. It's not critical, but really annoying.

**Comment by Quicksaver** [comment] 2016-01-19 18:38
I can't reproduce this. If you disable all your other add-ons, does this still happen? If yes, can you provide some specific steps to reproduce please?

**Comment by WolfganP** [comment] 2016-01-22 17:25
I'm suffering exactly the same issue. I assume the act of closing tabs makes FF jump to the previously last viewed tab, and when using Tab-Groups it seems the LRU queue is global instead of local to the group, so closing one tab may result in FF jumping to a tab in some other group which is kind of distracting.

**Comment by Quicksaver** [comment] 2016-01-22 17:27
@WolfganP have you tried what I asked above?

**Comment by IzziRoller** [comment] 2016-01-23 02:07
@Quicksaver: you right, this caused by  "All-in-One Gestures" extension. Tried to change some settings, no result. 
Disabled "All-in-one gestures", installed "Fire Gestures", seems problem solved.

Thank you

**Comment by Quicksaver** [comment] 2016-01-23 10:08
Hmm, all-in-one gestures hasn't been updated in three years, so it's likely problems like these will be increasingly common with new Firefox releases and new add-ons. You're probably better off with FireGestures because of that.

That said, if you do have a reason to stick with All-in-one Gestures let me know and I'll take a look to see if there's anything I can do.

**Closed by Quicksaver** 2016-01-23 10:08 UTC
Labels: bug, unconfirmed
