### ISSUE TITLE
Ctrl+Shift+T doesn't restore the tab in the right group

### ISSUE THREAD

**Issue by jvoisin** [Quicksaver/Tab-Groups#8] opened 2015-12-02 22:15 UTC
How to reproduce: `ctrl + w`, then `ctrl + shift + t`
Expected: The tab should be re-opened in the same group that it belonged, the actual one.
Actual: The tab re-opens in a new group.

**Comment by Quicksaver** [comment] 2015-12-02 22:34
> Actual: The tab re-opens in a new group.

New group or current group?

For me it reopens in the current group, which is expected because "reopening" is "opening" the last page that was there. If you "open" a tab, that always happens in the current group where you are. While it could be possible to reopen tabs in their original (inactive) group, that could only happen if the group still existed; i.e. it was not its last tab, in which case it would remove the group.

I'm not sure if this behavior would be helpful or just get in the way of someone's workflow...

**Comment by jvoisin** [comment] 2015-12-02 22:44
Actually, it opens in the same group, but all other tabs are hidden. I need to go to the *exposé* mode, to select the group again to make the other tabs visible.

**Comment by Quicksaver** [comment] 2015-12-02 22:49
What other tabs are hidden? And it opens in the group where you closed it after changing to another group? If that's happening, then I'm sure you have another add-on causing this behavior...

**Comment by jvoisin** [comment] 2015-12-02 22:54
I have 4 pinned tabs, and two open:
![1]( http://i.imgur.com/Q0xtjrj.png )

I close the github one:
![2]( http://i.imgur.com/QPupY9U.png )

I re-open it, with `ctrl + shift + t`, now it's alone:
![3]( http://i.imgur.com/T8eOgNe.png )

But it's actually in the group:
![4]( http://i.imgur.com/hon8JMg.png )

And if I select it, the other tab is here again:
![5]( http://i.imgur.com/Bf1fhoc.png )

**Comment by Quicksaver** [comment] 2015-12-02 22:58
Yes, that's what I meant, the github tab opens in the current group. The other tabs shouldn't have been hidden though, there must be a conflict with another add-on there is what I meant. Does the same happen if you disable all your other add-ons except for Tab Groups?

**Comment by jvoisin** [comment] 2015-12-02 23:08
I disabled and re-enabled my extensions, one by one, and … I can't reproduce the bug anymore :D

**Comment by Quicksaver** [comment] 2015-12-02 23:09
Well that's weird. :) Let me know if it happens again.

**Comment by dgutov** [comment] 2015-12-12 03:44
I've just had a similar problem, both when restoring a closed tab or opening a new one. This doesn't happen with a new session, but an existing one apparently can enter this state. Admittedly, I haven't tried it with other addons disabled yet.

Here's what I see in the error console:

```
tabview assert: should already be linked
TabItems_unlink@chrome://browser/content/tabview.js:5783:7
TabItems_init/this._eventListeners.close@chrome://browser/content/tabview.js:5557:9
_beginRemoveTab@chrome://browser/content/tabbrowser.xml:2237:13
removeTab@chrome://browser/content/tabbrowser.xml:2120:18
removeCurrentTab@chrome://browser/content/tabbrowser.xml:2091:13
BrowserCloseTabOrWindow@chrome://browser/content/browser.js:12916:3
oncommand@chrome://browser/content/browser.xul:1:1
...
tabview assert: shouldn't already be linked
TabItems_link@chrome://browser/content/tabview.js:5770:1
TabItems_init/this._eventListeners.open@chrome://browser/content/tabview.js:5541:9
addTab@chrome://browser/content/tabbrowser.xml:1889:13
loadOneTab@chrome://browser/content/tabbrowser.xml:1409:23
openLinkIn@chrome://browser/content/utilityOverlay.js:352:1
openUILinkIn@chrome://browser/content/utilityOverlay.js:190:3
BrowserOpenTab@chrome://browser/content/browser.js:12820:3
BrowserOpenNewTabOrWindow@chrome://browser/content/browser.js:18583:5
oncommand@chrome://browser/content/browser.xul:1:1
```

(version 1.0.1)

**Comment by Quicksaver** [comment] 2015-12-12 08:38
That output can't be from the add-on, as I've removed all the "assert"s in there. That could be either from the original tabview code in firefox from before it was disabled by the add-on during startup (which would make it harmless) or from another add-on trying to modify the add-on's code. Please try disabling all your other add-ons to confirm that the issue doesn't happen then.

**Comment by dgutov** [comment] 2015-12-12 13:12
> That could be either from the original tabview code in firefox from before it was disabled by the add-on during startup

No, these messages appear each time I try to restore a tab, or open a new one from the location bar.

> or from another add-on trying to modify the add-on's code. Please try disabling all your other add-ons to confirm that the issue doesn't happen then.

All right, but first I'll have to find a reproduction scenario. So far I'm still in the same session I had installed this addon in.

FWIW, I have only two Tab-related extensions installed (Tab Wheel Scroll and Undo Close Tab Replacement), and the only matches for `tabview` inside my extensions directory are in `tabgroups@quicksaver.xpi`.

**Comment by Quicksaver** [comment] 2015-12-13 14:32
> I have only two Tab-related extensions installed (Tab Wheel Scroll and Undo Close Tab Replacement), and the only matches for tabview inside my extensions directory are in tabgroups@quicksaver.xpi.

A conflicting add-on doesn't necessarily need to be tab-related. And it doesn't necessarily need to touch "tabview" code specifically either, there's tons of code (both in the add-on and in the original feature in Firefox) that is nowhere near that object.

**Comment by dgutov** [comment] 2015-12-13 14:56
After I restarted once, it was fine for a while, but I began seeing the problem again after a while, only then it manifested every other time, and (I think?) only in one of the tab groups.

I restarted again, and I can't trigger it now yet, but I see one error in the console that may be related:

```
item is null TabItems.jsm:1110:0
```

That line contains:

```js
	if(item.parent && (item.parent.isStacked() && !item.parent.isTopOfStack(item) && !item.parent.expanded)) {
```

But no "already be linked" errors yet. That's all I have for now. I can't really try toggling the addons on and off, unless I can't detect whether something's changed after a reboot, right?

Admittedly, the error log is littered with security errors from Adblock Plus, so it's a likely culprit. I'll try swapping it for uBlock Origin.

**Comment by Quicksaver** [comment] 2015-12-13 15:14
> item is null TabItems.jsm:1110:0

This appears sometimes. I haven't really figured out exactly what causes it but it seemed harmless in all the cases it's appeared for me; it's probably some asynchronous process trying to get data from a tab that doesn't exist anymore.

I doubt that has anything to do with this issue, otherwise I'd be having the issue a whole lot more frequently than you are.

> I can't really try toggling the addons on and off, unless I can't detect whether something's changed after a reboot, right?

If you can't find a reproducible case, as in exact steps where you're sure it will happen, then it'll be harder yeah. You could try disabling a few of them at a time for a while (day or two) and see if you ever run into the issue without them.

> Admittedly, the error log is littered with security errors from Adblock Plus, so it's a likely culprit. I'll try swapping it for uBlock Origin.

I'm sure those security errors have nothing to do with it. Those are more content-related.

**Closed** 2016-01-12 18:42 UTC
