### ISSUE TITLE
lost all tabs and groups on migration!

### ISSUE THREAD

**Issue by paleolith** [Quicksaver/Tab-Groups#113] opened 2016-02-21 04:46 UTC
I got the message about tab groups no longer supported by Mozilla. One of the main reasons I use Firefox! Whatever, I follow the instructions which say just install the Tab Groups extension and tab groups will be automatically migrated. Next time I restart FF, I have no tabs, no tab groups. There is no sessionstore.js in the profile. I colpy one a recover.js from the backups to the profile, rename it, still no tabs. What is going on? How do I get my tabs back?

Edward (very upset!)

**Comment by Quicksaver** [comment] 2016-02-21 09:32
It's possible, however unlikely, that your Firefox preferences were reset somehow to no longer restoring tabs and groups from a previous session. Please double-check in Firefox's preferences that "When Firefox starts" is set to "Show my windows and tabs from last time" (General tab) and that it is not set to clear history when Firefox closes (Privacy tab).

If that's not it, please try disabling all your other add-ons except for Tab Groups, restart Firefox, and then try your backup file again. By the way, how did you create that backup, did you manually copy the file yourself before?

If that doesn't work, try [creating a clean profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles), install the add-on there and try that backup there as well. That should at least let you know if the problem is with the add-on and with that particular session.

If it also doesn't work in the new profile, it's likely a problem with your session file. Try creating a new profile again (or simply delete all session information from that new one). Then in the add-on's preferences load that backup file in the add-on's backup and restore feature (you'll have to rename it to have a .json extension so the add-on recognizes it) and see if you can import your groups and tabs like that.

**Comment by paleolith** [comment] 2016-02-21 17:26
Thanks Luis! I got my tab groups back. The key was the file extension. I did not realize that FF was storing JSON data with a .js extension. When I tried to load an old sessionstore file, Tab Groups was looking for .json, and I didn't have any of those. I reloaded a day-old recovery.bak from backup (FF had already overwritten all the good files in the sessionstore-backups folder), renamed it to sessionstore.json, loaded it, and all is well. Almost, anyway -- as close as can be expected for going back a day.

The options are set as you describe. I did not need to create a clean profile.

I'm not sure how this was supposed to work. Was the conversion from the .js to .json extension supposed to happen automatically? There were no .json files when I tried to Restore Tab Groups / Load Backup File. I'm pretty sure there was no sessionstore.js either, although the backup files in the sessionstore-backups folder had been updated. And will sessionstore.json hold my Tab Groups configuration from now on? I have not yet restarted FF since recovering the tab groups.

To answer your question "how did you create the backup" -- I was obviously tired when I wrote that, as my words are jumbled! I was talking about recovery.js, previous.js, and recovery.bak in the <profile>/sessionstore-backups folder. I made copies of them as soon as I realized something was wrong. previous.js was a week old, so would have been useful but not the best. recovery.js might have worked if I'd realized that I needed to change the file extension. What I actually did today was to reload a day-old recovery.bak from backups (CrashPlan) and use that -- it was close enough.

Thanks again,

Edward

**Comment by Quicksaver** [comment] 2016-02-21 18:34
> Was the conversion from the .js to .json extension supposed to happen automatically? 

Hmm, there was not supposed to be any need for loading files at all, much less renaming them. You should have just needed to install the add-on, and it would re-use the groups you already had in your session from before. That's the weird part in all of this, your tabs and groups shouldn't have disappeared at all.

The only explanation I can come up with right now is that your previous session (the sessionstore.js file) was somehow corrupted or deleted when you exited Firefox that time. You should confirm that your Firefox options are set like I mentioned, just to make sure you don't lose your tabs when you restart Firefox again.

> And will sessionstore.json hold my Tab Groups configuration from now on?

Nope. If you check again you'll most likely have a new sessionstore.js file again in your profile folder. That will always be the file that holds your session data (unless some other add-on modifies this behavior, but I've never seen one do that). The sessionstore.json file is now nothing more than another backup you have.

Basically, if you use the add-on's backup feature, it will save the tabs and groups data in a .json file, and afterwards it only lets you load back from those files. But sessionstore.js is still a json file, it doesn't matter what extension it is (it's just a simple text file with data stored in a specific format). Except right now it only knows how to recognize the .json extension. I will change the load backup feature in the add-on to also recognize .js files, it makes sense to do that since Firefox's session files are stored as .js and they can be used to restore tabs and groups anyway. If I had done that already, I'm sure we could have avoided a lot of your trouble. :)

But at least you have your tabs back (for the most part), so I'll close this for now. Please do reopen and let me know if you lose them again after you restart Firefox, that's obviously not supposed to happen.

**Closed by Quicksaver** 2016-02-21 18:34 UTC
Labels: bug

**Comment by paleolith** [comment] 2016-02-21 19:42
OK, thanks. Yes, closing is fine.

I started wondering if FF was getting confused by the various copies of recovery.js that I had in my sessionstore-backups folder under various names. I moved them all into a subfolder, and now it appears that the restart is working properly. I had assumed that renaming them would be enough, but now it looks like perhaps FF scans all files in that folder, and obviously if it picked up one I was intending to hide, that would cause problems. Or something like that.

I was expecting to see a sessionstore.js in the profile. Just now, I was watching the profile folder as FF started, and I saw that file appear -- and then disappear. So I guess FF creates it but then moves it to the sessionstore-backups folder. The instructions for copying a backup as sessionstore.js must be just for recovery, not because sessionstore.js is normally present.

I also now have a suspicion that the loss of tabs resulted from a combination of PEBKAC and one of FF's known problematic behaviors. I usually have only one FF window open, except when I have a tab that's hard to read in a wide window. Last night, I restarted FF because a form in one tab was not operating properly. I'm pretty sure I did the quit by closing the window (x in upper right). Did I have a second window open? I was tired and I can't say for sure. But if I did have a second window open, then closing the main window would have been just that, closing the window rather than quitting FF, and the fact that the window had been closed would be reflected in the recovery.js. I'm pretty sure I did **not** use file/exit or alt-F4, which are the methods that retain the window/tab configuration. (I've dealt with this part of the FF UI before. I find it confusing and dangerous, and when I feel that way, it usually turns out that a lot of other people feel the same. But I'm probably preaching to the choir.)

So I now think the loss of tabs and groups after the conversion was a coincidence, and was likely caused by this known, problematic behavior in FF.

Thanks yet again,

Edward

**Comment by Quicksaver** [comment] 2016-02-21 19:48
> I'm pretty sure I did the quit by closing the window (x in upper right). Did I have a second window open?

That's gotten me a couple of times as well. :) When this happens, most times you can get that window back by going to the History menu and reopening it from the "Recently closed windows" entry, even after you've restart Firefox since it will still be the same session. I think there's also a toolbar button for that, you might want to keep it in hand, maybe in the menu panel (in the "three bars" / hamburger button) where it'll be out of the way unless/until you need it.

**Comment by paleolith** [comment] 2016-02-21 19:53
Yeah. The problem is realizing what happened. ;-)

Cheers.

**Comment by Quicksaver** [comment] 2016-02-21 19:54
So very true. ;)
