### ISSUE TITLE
Tabs won't stick to their groups.

### ISSUE THREAD

**Issue by olymind1** [Quicksaver/Tab-Groups#93] opened 2016-02-05 15:22 UTC
I disabled all of my addons except of course this one.

I have a few groups, i place tabs in them, i close firefox, i open firefox, the group that is active when firefox starts, it sucks tabs from other groups.

It remembers the groups and their names, they are just empty of tabs.

If i remeber correctly It started happening after a firefox crash, i had crashes sometimes, but this din't happen before.

**Comment by Quicksaver** [comment] 2016-02-05 15:26
Can you try something for me please, restart Firefox with all add-ons disabled except for Tab Groups. As soon as it starts, open the browser console (Ctrl+Shift+J) and see if there are any warning or errors about tab groups in there. Then clear it but don't close it. In the main browser window, go into groups mode. Did anything appear in the console now?

If you're in doubt about the messages in the console being about tab groups, just copy the whole thing into a text document and attach it here (or copy it here directly even).

**Comment by olymind1** [comment] 2016-02-05 15:34
After start: 

`Could not read chrome manifest 'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.
While creating services from category 'profile-after-change', could not create service for entry 'Sapi Speech Synth', contract ID '@mozilla.org/synthsapi;1'
[CustomizableUI] Custom widget with id loop-button does not return a valid node CustomizableUI.jsm:166
Warning: attempting to write 4931 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-ee521b8e9facac68ff27e93fc3ae0f8ed811d7bf9e434e84f4b9ea227780b084.js:1:20147
A getElementById() üres karakterláncot kapott. github-3414864a43b9ec8feb81829c899f8b54f9becd1e54e3b38c46f23f176d58ada6.js:6:11478
A billentyűesemény nem érhető el egyes billentyűzetkiosztások esetén: key="c" modifiers="accel,alt" browser.xul
A billentyűesemény nem érhető el egyes billentyűzetkiosztások esetén: key="i" modifiers="accel,alt,shift" browser.xul`


I clearing the log, opening the tab group nothing changes, when i move tabs between groups:

`Unable to get scrollbar size in determineCropSize. PageThumbUtils.jsm:115:0
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/PageThumbUtils.jsm :: this.PageThumbUtils.createSnapshotThumbnail :: line 193"  data: no] TabItems.jsm:869:0
Egy kiegyensúlyozatlan fa document.write() használatával történt kiíratása a hálózatról származó adatok újrafeldolgozását okozta. További segítség: https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing encyclopedia.php:25:0
Egy kiegyensúlyozatlan fa document.write() használatával történt kiíratása a hálózatról származó adatok újrafeldolgozását okozta. További segítség: https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing project.php:25:0
`

**Comment by Quicksaver** [comment] 2016-02-05 19:31
Are you using an add-on called Session Manager by any chance?

**Comment by olymind1** [comment] 2016-02-05 19:39
Yes, i am. But if i disable it, then does it really matter?

**Comment by Quicksaver** [comment] 2016-02-05 19:49
Normally it shouldn't, but if it's somehow saving wrong/corrupt groups information in the session file, then it will persist even when disabled... I asked because of #83 which looks almost the same as this.

I'll investigate Session Manager's code this weekend, I know it included specific fixes for this Tab Groups add-on in its last update, so maybe that's what's causing this regression as well.

**Comment by olymind1** [comment] 2016-02-05 19:52
Hmm, Tab Groups v1.02 worked fine for quite a while. Maybe it is Session Manager update indeed.

BTW the default firefox tab groups save the tabs correctly.

**Comment by Quicksaver** [comment] 2016-02-07 13:46
A new update for Session Manager was just released that includes a fix for compatibility with Tab Groups. Please update it, reconfigure your groups and tabs (**after** updating Session Manager) and see if they stick after exiting and reopening Firefox.

**Comment by olymind1** [comment] 2016-02-08 08:14
Updated Seesion Manager, enabled Tab Groups, restarted FF, sadly the starting group automatically collected tabs from other groups.

**Comment by Quicksaver** [comment] 2016-02-08 10:06
Any groups information is usually only saved when you make any changes to it, as it assumes the previous info was also correctly saved. That's why I said you'd have to rearrange/resort everything after updating SM, because only then the groups info would actually be saved into the session. ;)

**Comment by Quicksaver** [comment] 2016-03-13 15:56
Did this ever happen again since updating Session Manager?

**Comment by Quicksaver** [comment] 2016-03-22 19:22
I'm guessing not. :)

**Closed by Quicksaver** 2016-03-22 19:22 UTC
Labels: bug
