### ISSUE TITLE
Automatic Grid Layout

### ISSUE THREAD

**Issue by RageYL** [Quicksaver/Tab-Groups#13] opened 2015-12-04 10:13 UTC
Hi,

Is it possible to implement an automatic grid layout ? 
Groups would be automatically arranged in a grid layout. (no need to resize and move groups)

Thanks

**Comment by Quicksaver** [comment] 2015-12-04 10:25
I've been thinking about this as well, it should be possible. Not sure if it's doable though.

**Comment by Aybee** [comment] 2016-01-14 23:05
Just wanted to ask the same feature request. Maybe this library will help you to get it done http://isotope.metafizzy.co/

**Comment by GRX00** [comment] 2016-01-27 21:36
Looking forward for this functionality - it is really annoying sometimes when you add new group and it mess up all other ones and even simple place in grid would be better than mess

**Comment by norpol** [comment] 2016-03-17 09:20
I'd also welcome a more tiling based tab group system. :)
Going to support you via. [paypal](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) soon.

**Comment by Quicksaver** [comment] 2016-03-22 19:11
In [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1). Help me test it? :)

**Comment by DuckOfDuckness** [comment] 2016-03-22 19:25
Where do you want feedback for that beta?

**Comment by Quicksaver** [comment] 2016-03-22 19:30
Here, you're welcome to reopen if you find big issues or have some suggestions for improving it further. You can open new issues for smaller/more specific things if you prefer. Use your best judgement. ;)

**Comment by RageYL** [comment] 2016-03-22 20:49
Thanks for this update :)
It would be great to be able to choose how many rows/cols there is or be able to limit the number of groups by row. (i have too many groups, the second row is too crushed).
Apart from that, this is very good ;)

**Comment by RageYL** [comment] 2016-03-22 20:54
Thanks for the update !
I think it would be great to be able to limit the number of groups by row or be able to choose how many rows/cols we want (i have too many groups, 2 rows is not enought).
Apart from that, this is very good ;)

**Comment by Glaived** [comment] 2016-03-22 20:56
@Quicksaver @RageYL 
![sans titre 2](https://cloud.githubusercontent.com/assets/1835170/13967695/dfa0d05e-f078-11e5-8184-639f9feb6178.png)

**Comment by Quicksaver** [comment] 2016-03-22 21:00
@RageYL can you post a screenshot? I've been thinking about setting a larger minimal width, so that groups aren't compressed as much; technically it should give you more than two rows when necessary, so it's probably not reaching the necessary minimum width for that yet.

@Glaived would that work for you as well? I'm guessing larger groups overall would mean the new group button would be a lesser inconvenience, but I could be wrong. I don't dislike your suggestion, but the reason I left it like this is because you can drag tabs there to create new groups; that won't be so easy with a smaller button on the side.

**Comment by RageYL** [comment] 2016-03-22 21:08
I upvote the proposal of @Glaived ;)

![screenshot-1458680617](https://cloud.githubusercontent.com/assets/7813795/13967993/6140c0b4-f07a-11e5-855a-ad59583f1fe6.jpg)

**Comment by iShyboy** [comment] 2016-03-22 21:14
Less intrusive plus button would be good, more screen for other groups.

**Comment by DuckOfDuckness** [comment] 2016-03-22 22:01
The bottom row is like _really_ squished.
![firefox_2016-03-22_22-55-27](https://cloud.githubusercontent.com/assets/1951003/13969177/8aca82c4-f081-11e5-8d1b-ba5b4f0151c2.png)
For me the "new group" button actually has a nice size though.

**Comment by Quicksaver** [comment] 2016-03-22 22:25
Yep, it definitely needs some tweaking overall...

**Comment by Glaived** [comment] 2016-03-22 23:27
@Quicksaver you did a great job, we expect all thy neighbor PR :D

sowwi for my bad English but Google Translate really sucks xD

**Comment by Aybee** [comment] 2016-03-23 11:04
Seems not to work together with https://addons.mozilla.org/de/firefox/addon/tab-groups-helper/

Can you please test this? Where I first saw my 12 groups within tab-groups-helper I now see 12 empty groups with no group title. But groups are still there as I can see with Tab-Groups.

After downgrading to stable Tabgruppen 1.0.2 all is fine again.

**Comment by Quicksaver** [comment] 2016-03-23 11:06
> Seems not to work together with https://addons.mozilla.org/de/firefox/addon/tab-groups-helper/

One of the things that should be in its own issue... But I'll take a look.

**Comment by Aybee** [comment] 2016-03-23 11:28
> One of the things that should be in its own issue...

Yes, I thought about that to. Thank you for taking a look.

**Comment by Quicksaver** [comment] 2016-03-25 11:03
> I think it would be great to be able to limit the number of groups by row or be able to choose how many rows/cols we want (i have too many groups, 2 rows is not enought).

I **may** add something like this, eventually. But that's not as easy to do as it sounds, so for now I'm sticking with trying to improve the automatic layout. In the end, if it ends up working well enough, that may not even be necessary then.

**Comment by Quicksaver** [comment] 2016-03-31 23:12
[Beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) should keep a larger aspect ratio for groups while in grid mode. Please try it out and let me know if you think it can still be further improved.

**Comment by iShyboy** [comment] 2016-03-31 23:35
While you did a good job in the grid layout, something went off in the arrange mode, tabs got stacked too easy, some groups that easily showed 100+ tabs, even with all my screen, it still got stacked with the addon.
![addon] (http://i.imgur.com/6LGQo1G.png)
![default] (http://i.imgur.com/6LGQo1G.png)

**Comment by RageYL** [comment] 2016-04-01 07:26
I don't know if anybody will agree with me but i would prefer groups having the same size. (it should be even easier to implement)

**Comment by Quicksaver** [comment] 2016-04-01 09:28
It uses a dynamic layout, meaning that the top groups will have an increased size only if there is space for it. At most, the top groups should only be twice as big as the lower ones, is that difference too big?

**Comment by Quicksaver** [comment] 2016-04-01 10:00
@iShyBoy there are some differences in the item sizes, group sizes, and all-around layout handlers between the add-on and the old native groups (basically, free arrange mode is not equal to native groups), it's really not fair to compare the two anymore. ;)

**Comment by DuckOfDuckness** [comment] 2016-04-01 10:06
It might still be too big a difference. I have 2 Firefox windows, each with their own issue. My main window is below. Notice how much empty space there is in each top-row group:
![firefox_2016-04-01_11-41-13](https://cloud.githubusercontent.com/assets/1951003/14203533/db8986fe-f7fe-11e5-96a9-2ea42c676a74.png)
And here is my second window. It doesn't seem to have been affected by the change in v2b2 at all actually, and still looks like v2b1 (bottom row is really squished and has a lot of empty space in the two groups):
![firefox_2016-04-01_11-44-47](https://cloud.githubusercontent.com/assets/1951003/14203584/3365b60e-f7ff-11e5-89d6-84efb4e79750.png)

The prettiest solution would probably be for the addon to attempt to always "fill out" a group so there's a minimum amount of empty space in it. A group of 4 tabs would be 2x2 and square, a group of 3 tabs would be 3x1 or 1x3 and either tall or wide, respectively.

I'm not really sure how doable that is, though. And it also means that every time a new tabs is opened or closed the whole layout may have to change since the group goes from square to wide or back. Might not be worth the effort required.

Great work you're doing though. No complaints!

**Comment by Quicksaver** [comment] 2016-04-01 10:16
> Notice how much empty space there is in each top-row group

True. That is happening because the groups don't actually have enough space to wrap the last tab. For instance, the second and third groups, if it were to place the last in a new row, the tabs overall size would increase, and it would be cropped at the bottom (tabs maintain a constant width to height ratio).

I already plan to do a lot with the tab items thumbnails, to reduce this effect as much as possible. But I'm leaving that for after some other things I want to work on first. But it doesn't really have to do with grid layout (you can achieve the same effect in free arrange mode if you try).

> bottom row is really squished and has a lot of empty space in the two groups

That's... really not supposed to look like that... Let me see if I can reproduce it.

**Comment by Quicksaver** [comment] 2016-04-01 10:35
@DuckOfDuckness about that second screenshot, do the groups arrange properly if you resize the window?

If not, can you please install [beta version 2b2.1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2.1), it's unsigned so you'll have to disable ```xpinstall.signatures.required``` in about:config first. Then open the browser console (Ctrl+Shift+J), clear it, and in that window enter groups mode. Back in the console there should be at least one entry with a bunch of calculated sizes, can you post that here please?

**Comment by DuckOfDuckness** [comment] 2016-04-01 11:05
> about that second screenshot, do the groups arrange properly if you resize the window?

Actually yes. I just played around with it a bit, and it seems to mess up once the height goes from 1181 to 1182, regardless of window width, and only if there are 2 rows. So at 1181 window-height it looks normal, but any taller than that and the bottom row gets squished.

**Comment by Quicksaver** [comment] 2016-04-01 11:11
That's weird, can you get me the debug strings I asked anyway? One for when it squishes (1182px or above) and one for when it looks normal (1181px or below). I'd like to know what part is screwing up.

**Comment by Quicksaver** [comment] 2016-04-01 11:26
Hold on, I managed to reproduce it.

**Comment by Quicksaver** [comment] 2016-04-09 16:59
[Beta version 2b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b3). Tweaked things a little again, those highly compressed groups should no longer happen. We should be close now, if we're not there already. ;)

**Comment by Glaived** [comment] 2016-04-09 20:49
What do you think this way:

When **<= 3 groups** OR **>= *x* tabs on one group**
![1](https://cloud.githubusercontent.com/assets/1835170/14406288/23767d86-fea4-11e5-8a19-de221b195d4c.png)

When **> 3**: functionality and current layout.


With the new layout, which can handle a large number of groups, it requires us to change tabs with two clicks, whereas before one was enough.
My proposal will keep the speed when you have little groups, and keep the good management when you have lots of groups.
What do you think ? @Quicksaver

**Comment by RageYL** [comment] 2016-04-09 22:32
About the new version: i like very much the scroll mode and the new 'Single View' layout.
Otherwise, as i have already said, i would love a fair layout, with all groups having the same size =)

When stacked some scrolls appears: is it the intended behaviour ? (seems useless to me)
![image](https://cloud.githubusercontent.com/assets/7813795/14406796/7cbd2d22-feb3-11e5-8202-8e7e39831a3c.jpg)

**Comment by Quicksaver** [comment] 2016-04-09 23:04
@Glaived I really don't understand what you mean. Especially this part:
> With the new layout, which can handle a large number of groups, it requires us to change tabs with two clicks, whereas before one was enough.

How so? It should only take a single click on any tab to switch to it. Unless you mean when a group is stacked and you have to expand it, but that behavior hasn't changed, so... Can you clarify please?

> When stacked some scrolls appears: is it the intended behaviour ? (seems useless to me)

@RageYL definitely not, I'll try to reproduce it to see what's happening there. I already have an idea of what might be going on though, and it should be easy to fix. Also:

> Otherwise, as i have already said, i would love a fair layout, with all groups having the same size =)

You know what, I went back to your comment about that, and I have to admit I completely misread it at the time (which you can probably guess from my response immediately after). I'm sorry about that. 

Indeed an option to keep the same size in all groups is pretty easy, but is there a big gain in doing it? The difference isn't all that much already, and you can use it to your advantage to sort your groups into "more important" ones at the top, where you may like to keep its tabs visible, and "less important" ones (maybe with a lot of tabs) stacked at the bottom.

Not saying I won't do it though, just discussing it at least, as I'd like to keep things as straightforward as possible. Is it just a matter of personal or do you think you would actually benefit from it?

**Comment by Glaived** [comment] 2016-04-10 06:23
### With v2b3 (2 clicks needed)
![animation 0](https://cloud.githubusercontent.com/assets/1835170/14408419/c1a7337e-fef4-11e5-8ea8-9d9f5ebcd87d.gif)



### With v2b2 (just one click needed)
![animation 1](https://cloud.githubusercontent.com/assets/1835170/14408423/cf34b41c-fef4-11e5-919c-8a702209b004.gif)

The 2b2 version is faster, but mismanaging the tabs when there are many, 2b3 is the inverce. The best would be to have an functioning as the 2b2 release when there is little tabs, and 2b3 when there is full.

**Comment by RageYL** [comment] 2016-04-10 08:55
@Quicksaver : don't appologize, it's my bad too =)

After reading your explanations, i think it would not benefit that much. so forget the idea for now. If i really miss it i would create a new thread ;)

**Comment by DuckOfDuckness** [comment] 2016-04-10 09:10
New windows seem to have no tab group functionality. Pressing the "Group your tabs" button or using the keyboard shortcut does nothing in a new window, and neither does right-clicking a tab and selecting 'Move to Group -> New Group'.
My old windows from before installing 2b3 still work fine and there's no longer any weird squishing, so the problem is only _new_ windows.

**Comment by Quicksaver** [comment] 2016-04-10 10:29
@Glaived I guess I should have clarified that... That's a new mode called single view, tracked in #46. You can still toggle between single view, grid layout and free arrange mode using the buttons on the right. ;)

**Comment by iShyboy** [comment] 2016-04-10 10:57
The single view is making wonders, I'm very pleased with it, the function to scroll too, albeit difficult to move small groups in the unorganized mode.

**Comment by Quicksaver** [comment] 2016-04-10 11:10
> albeit difficult to move small groups in the unorganized mode.

How so?

**Comment by iShyboy** [comment] 2016-04-10 11:23
![groups](http://i.imgur.com/tJESLmh.png)
Its hard, near everything in a small scrollable group, it move the tab, not the group, there's jus a fine line on the top that makes the group draggable.

@Quicksaver in the single view mode, there's any need for the thumbnails in the top groups? They're now small, and we can't get anything from them, we'll guide ourselves by the names, so there's any need for them? Put a separator between the groups on the top, and we have more height for the opened group.

**Comment by Quicksaver** [comment] 2016-04-10 11:41
> Its hard, near everything in a small scrollable group, it move the tab, not the group, there's just a fine line on the top that makes the group draggable.

You should be able to drag from its title as well, as long as the cursor isn't already there.

> in the single view mode, there's any need for the thumbnails in the top groups?

You should have asked this in #46. ;)

For now at least yeah because groups can still have empty names. I can consider **optionally** removing those thumbs, when I make it show something like "Unnamed group 123" when there's no name defined. But single view is really conceptualized for an almost completely visual navigation, I really only added the group titles to those as well because why not. ;)

**Comment by iShyboy** [comment] 2016-04-10 11:45
@Quicksaver true, I was fooled by the ibean cursor, never tried to drag by the title.

**Comment by PR0PH3T** [comment] 2016-04-11 22:59
I don't want to make a new issue just for this so i'll post my idea here.

While the list view is a neat idea i don't find it very helpful. What i would like is to be able to find the group that i'm looking for at a glance. What i would like to propose instead is an option that would let you chose to use the website's favicon and the most representative color instead of thumbnails.

Basically something like this: [http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html](http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html)

I think it could be a nice feature but i could be wrong, just an idea i would like you to consider.
Either way thanks for your time and for developing this addon.

**Comment by gimoh** [comment] 2016-04-13 11:57
>> Otherwise, as i have already said, i would love a fair layout, with all groups having the same size =)

> Indeed an option to keep the same size in all groups is pretty easy, but is there a big gain in doing it?
> The difference isn't all that much already, and you can use it to your advantage to sort your groups into
> "more important" ones at the top, where you may like to keep its tabs visible, and "less important" ones
> (maybe with a lot of tabs) stacked at the bottom.

> Not saying I won't do it though, just discussing it at least, as I'd like to keep things as straightforward as
> possible. Is it just a matter of personal or do you think you would actually benefit from it?

It might be a matter of preference but I'd also like the option of having all groups equal size and adjusting the size based on number of groups and available space in the window.  I suppose it comes down to the fact that I don't have more or less important groups, they're all important so I'd like them to be equally visible.

Wouldn't this be easier to do rather than the magic/smart mode?

**Comment by Quicksaver** [comment] 2016-04-13 18:05
Added an option to disable dynamic sizing in grid layout in [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4). It's not something I particularly agree with, but it's easy to implement so there's no reason not to make everyone happy. :)

Also, there shouldn't be any more trouble in updating from an older version, but if you do run into any major problems updating (like losing groups, or seeing all tabs merged into a single group, or things like that), please let me know in #178.

**Comment by Quicksaver** [comment] 2016-04-13 18:06
Oh and fixed the scrollbar appearing in stacked groups thing.

**Comment by Quicksaver** [comment] 2016-04-26 14:36
Unless I missed something, with the latest bugfix in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5), I guess we're done here. Feel free to open new issues if you have any suggestions to further improve it or if you run into any trouble.

**Closed by Quicksaver** 2016-04-26 14:36 UTC
Labels: enhancement

**Comment by Aybee** [comment] 2016-04-26 16:16
Please test it with https://addons.mozilla.org/de/firefox/addon/tab-groups-helper/ It still did not seem to work together with this addon.

comment above:
https://github.com/Quicksaver/Tab-Groups/issues/13#issuecomment-200297813

**Comment by Quicksaver** [comment] 2016-04-27 09:48
@Aybee #188.

**Comment by Aybee** [comment] 2016-04-27 10:25
Thank you.
