### ISSUE TITLE
Wrong Warning about Tab Saving : way to disable it or support session manager ?

### ISSUE THREAD

**Issue by whismerhill** [Quicksaver/Tab-Groups#141] opened 2016-03-14 01:29 UTC
In short, since I'm not using Tabgroups to save my tabs it's warning me about it.
Would it be possible to disable the warning or detect the existance of an addon that handles session saving such as session manager ?

SIDENOTE: I'd strongly advise anyone with large sessions to start using session manager, with this addon I never lost a session anymore. whereas firefox built in session saving can definitely fail.
settings I recommend :
number of backups to keep : 50
new backup : each 60min 
number of days to keep deleted sessions : 7

Sorry if this is not formatted correctly, first time using github.
Thanks for reading.

**Comment by Quicksaver** [comment] 2016-03-14 09:15
It should detect Session Manager. What do you have set for "At startup always load the following session" in its preferences?

**Comment by whismerhill** [comment] 2016-03-17 04:35
I have enabled the "prompt for a session" setting
sorry for the late reply

**Comment by Quicksaver** [comment] 2016-03-17 09:03
I will check it out, it could be, although I thought I had set it to not show the warning when using that setting.

**Comment by mirh** [comment] 2016-03-20 16:25
I turned on [browser.showQuitWarning](http://www.ghacks.net/2014/02/11/configure-firefox-show-quit-warning-exit/) and I also find the warning redundant, since **Save and Quit** already does the trick. 
Since I guess you put it there for a reason, I wonder: is that only about "*Show my windows and tabs from last time*"?

Also, this should be duplicated of #122

**Comment by Quicksaver** [comment] 2016-03-20 17:39
> I turned on browser.showQuitWarning and I also find the warning redundant, since Save and Quit already does the trick.

Opened #152 for this.

> Since I guess you put it there for a reason, I wonder: is that only about "Show my windows and tabs from last time"?

Yes and similar preferences from other session-related add-ons.

> Also, this should be duplicated of #122

Not quite, that issue should have been closed a while ago. This issue is different, it's more of a "it's not detecting Session Manager's settings properly". I set it as a duplicate of this one instead, in case I misunderstood that other issue though.

**Comment by mirh** [comment] 2016-03-20 18:36
> Yes and similar preferences from other session-related add-ons.

"Similar preferences from other tools" shouldn't be your [direct] business tbh. 
I mean.. wouldn't a "blacklist" approach be way simpler than the current "whitelist" one?

Or even better, why the addon couldn't work with "default" tab saving?

**Comment by Quicksaver** [comment] 2016-03-20 18:40
> "Similar preferences from other tools" shouldn't be your [direct] business tbh. 

I meant for when keeping the session across browser restarts when not using the native session manager; i.e. Session Manager or Tab Mix Plus.

> I mean.. wouldn't a "blacklist" approach be way simpler than the current "whitelist" one?

How would that work? Either it knows about a tool keeping a session or it doesn't. It can't just guess.

> Or even better, why the addon couldn't work with "default" tab saving?

It does, it's the "Show my windows and tabs from last time" preference. Unless I'm missing something. I didn't know about the ```browser.showQuitWarning``` preference until now, so, point above, it can't guess it exists.

**Comment by mirh** [comment] 2016-03-20 19:49
Oh, I see that now. 

So, my stupid questions were now: isn't there some way to detect when native session manager is **not** used?
And why can't you fix "show ... from last time" by default? Is there any downside?

**Comment by Quicksaver** [comment] 2016-03-20 19:54
> isn't there some way to detect when native session manager is not used?

This is a very (very!) rough approximation of what's going on, but short answer is: no. ;)

Every session manager implements itself differently, which is to say they disable the native session manager differently. For instance, Session Manager actually uses the same preference, it just uses different methods backstage to actually handle the session-ing things. Tab Mix Plus uses an entirely different set of preferences.

And none of those fully disable the native session manager, otherwise they wouldn't work with pretty much every other add-on out there because that's what everything uses, they just... take over its "API" so-to-speak. (If every add-on had to rewrite itself to work with three or more different session systems it would be chaotic and just impossible to manage.)

> And why can't you fix "show ... from last time" by default? Is there any downside?

Fix what exactly? I don't follow.

**Comment by mirh** [comment] 2016-03-20 20:36
> Every session manager implements itself differently, which is to say they disable the native session manager differently.

And I guess that if it could just be as simple as detectomg whether that's still completely in place (settings or whatever) you'd already have done it :s

> Fix what exactly? I don't follow.

Why you require people to press the button in options, instead of doing that on first launch?

**Comment by Quicksaver** [comment] 2016-03-20 20:37
> Why you require people to press the button in options, instead of doing that on first launch?

It does automatically enable it when the add-on is first installed. ;) If it wasn't for you then it's likely another add-on you have must have reset the preference.

**Comment by whismerhill** [comment] 2016-03-21 02:04
tell me if you want/need any more testing or information. Note that as far as I'm concerned a simple "ignore warning" checkbox in the options would be just fine since it otherwise works.

**Closed** 2016-03-30 16:59 UTC
Labels: bug, important

**Comment by Quicksaver** [comment] 2016-03-31 23:09
[Beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) should no longer show the warning when you set Session Manager to prompt for a session at startup. Please let me know if you try it out and find any issues.

**Comment by whismerhill** [comment] 2016-06-01 01:19
sorry I couldn't manage this any earlier. tried beta v2b10, even restarted firefox to be sure, same issue

**Comment by Quicksaver** [comment] 2016-06-01 07:17
There is also a checkbox in the add-on preferences now, to disable those warnings. But still, the warning shouldn't appear at all if you still have session manager prompting at startup. I'llcheck it out.

**Comment by whismerhill** [comment] 2016-06-02 11:59
Didn't notice the option, thanks for that :)
I'm a *happy camper* now
