### ISSUE TITLE
suggestions: "+" new group button & default/templates groups 

### ISSUE THREAD

**Issue by Bumbadawg** [Quicksaver/Tab-Groups#322] opened 2016-06-09 19:18 UTC
Thanks for making such awesome addons, appreciate it a lot :-)

# First suggestion
I use the group button in the tab bar by default, since there is a "+" button to add a new tab, it'd be cool to have a "+" button to add a new group. It could come with flavours like:
- add a new temporary group so my aunt browses a bit,
- add a new private temporary group (based on https://addons.mozilla.org/en-US/firefox/addon/private-tab/ ), so i can use clean cache for web tests, or other means :3

# 2nd suggestion: templates/default groups
It'd be cool to have default/templates groups. For instance: 
- multimedia (youtube, spotify, etc),
- news sites,
- social (twitter, reddit, facebook, linkedin, etc),
- utilities (translate, map, phonelist, etc),
- main (others),

# 3rd suggestion: tagging and automatic organizing.
Let's suppose we are googling / duckduckgoing some youtube video : the new tab opens in the media group. 
- If We close the video, we go back to our previous visited group.
- If we changed tab in the meantime there is no going back.

Now we open a news related site > the tab goes into news group.
We are on a news site, we click on the last Trump stupid twit : the twit opens into the social media group.
But we could also choose not to use our twitter account to open this twit and open the tab into our private temporary group.

I hope this is not too messy.
Keep up the good work Luís Miguel, love your contributions :)

**Comment by Quicksaver** [comment] 2016-06-09 19:37
Please let me know if I misunderstood anything below, as I believe you can already achieve most of what you want.

> I use the group button in the tab bar by default, since there is a "+" button to add a new tab, it'd be cool to have a "+" button to add a new group.

This does exist in single view and in grid layout, but it's impossible to add this in free arrange, because new groups currently can screw up the whole layout. It's better to just drag and drop them there.

>  add a new temporary group so my aunt browses a bit,
    add a new private temporary group (based on https://addons.mozilla.org/en-US/firefox/addon/private-tab/ ), so i can use clean cache for web tests, or other means :3

Can't you achieve all of that by simply creating new groups? Create new group -> open private tab = group is now private. Create new group -> browser for a bit -> close it later = temporary group. Did I miss something? :/

> It'd be cool to have default/templates groups.

Having default groups in the add-on would be far too arbitrary IMO, and having user-defined default groups is the same as creating new groups anyway. So, same as above? You can also simply backup your groups and use that as "defaults" that you would restore at a later time.

> tagging and automatic organizing.

Most of that you can do with the catch rules already, am I missing something here? Except for:

> If We close the video, we go back to our previous visited group.

... which would be incredibly hard to keep track of and prone to wrong behavior I believe. While I can see the use in this, I think its benefit doesn't compensate the cost of implementing it and keeping it working correctly.

**Comment by Bumbadawg** [comment] 2016-06-09 20:30
Right, i can agree on each of your answers.
And about the arbitrary defaults, yes that's maybe not a good philosophy.

> Most of that you can do with the catch rules already

Oh wow didn't see it! :heart: 
Maybe a list of tags / catch rules in the group title could help noobs like me see it at a glance. e.g. : 
**[*] Favourites [*.github.com] [*.reddit.com] [+]**
Clicking them could dismiss them (just convenience like other suggestions i just made).

> ... which would be incredibly hard to keep track of and prone to wrong behavior
you'd need 2 variables to store the state. For instance:

- i go in _media_ group
- `selected_group = "media"`
- `current_group = "media"`
- a link in _media_ group opens twitter, catch rule opens it in the _social_ group.
- `current_group = "social"`

if i change to any other tab / group in the meantime:
- `selected_group = current_group`

else if i close the tab:
- `openGroup( selected_group );`

**Comment by Quicksaver** [comment] 2016-06-10 08:37
> Maybe a list of tags / catch rules in the group title could help

Some of those rules can become very long and may not be easy to read at first glance, which would make it just impractical I believe.

> you'd need 2 variables to store the state.

The problem isn't holding the info, it's using it properly. ;) In those simple situations it would be simple to follow, but there are many ways a tab can be closed, switched, etc. I don't believe this will happen.

**Closed by Quicksaver** 2016-06-10 08:37 UTC
Labels: enhancement, wontfix

**Comment by Bumbadawg** [comment] 2016-06-10 09:03
alright :)
