### ISSUE TITLE
Recover Lost Tab Groups

### ISSUE THREAD

**Issue by david4sure** [Quicksaver/Tab-Groups#178] opened 2016-04-10 23:44 UTC
Hi Guys
Great solution.
For some reason (possibly a crash) i have lost all tab groups.
I back up my machine regularly and can restore individual folders or files fairly easily.
Is there a way i can recover all my lost tab groups from my backup? Is there a folder or directory i can restore?
Any help would be greatly appreciated.
Thanks
David

**Comment by iShyboy** [comment] 2016-04-10 23:47
Because of some crash, I thought that I lost all my groups, but I did not, after I installed 2b3 and restarted FF it crashed and when I restarted after the crash, it opened up with a new tab, but it did have 253 tabs opened according with tab count. Dunno if your problem its the same though.

**Comment by david4sure** [comment] 2016-04-11 00:05
Hi. Thanks for the reply. im not sure what '2b3' is sorry. But no, i have restarted a few times and haven't got me tab groups back

**Comment by iShyboy** [comment] 2016-04-11 00:11
Last beta release of the addon, in my case, the groups didn't show up even on tabs groups, but when I tried to backup the session with the addon, I saw that every tab that I had transformed in a single group, so that I had 253 groups, and annoyingly I could only to the thing manually and after all the effort I re-organized my session down to 96 tabs YAY!
If you lost your session, and firefox don't show the restore session on about:home, or you don't have session manager, or another addon that do this for ya, I can't think anything at all to help you.

**Comment by david4sure** [comment] 2016-04-11 00:26
HI

Thanks again for the reply. When you say "or you don't have session manager, or another addon that do this for ya" firstly, no i dont, secondly, are there add ons out there that do this?

**Comment by iShyboy** [comment] 2016-04-11 00:32
Yes [Session Manager](http://sessionmanager.mozdev.org/) its addon that does this wonderfully, it even has an auto backup function that backup your session at a set time(you can change it).
@Quicksaver already recommended it in some issue out there, I too did this. As a tab lover I tend to have a lot of then.

**Comment by Quicksaver** [comment] 2016-04-11 09:25
Have you tried in the default homepage (about:home) or in the History menu selecting "Restore previous session"? More often than not, that works, as long as you haven't quit Firefox in the meantime (overwriting the previous session again).

If that doesn't work, the file where this is all stored is sessionstore.js, in the root of your Firefox profile folder.

**Comment by iShyboy** [comment] 2016-04-11 10:54
Quite hard for him to recover now.

**Comment by Quicksaver** [comment] 2016-04-11 11:00
Not necessarily. Many times it's still possible to get back at least something. ;)

**Comment by iShyboy** [comment] 2016-04-11 11:10
All to his luck, if he already said that he restarted a few times, and if he got some ccleaner or the like, it would be hard.

**Comment by david4sure** [comment] 2016-04-11 11:17
What if i restore the Firefox folder from my back up. From a few days ago?

**Comment by Quicksaver** [comment] 2016-04-11 11:27
If you mean your [profile folder](http://kb.mozillazine.org/Profile_folder_-_Firefox) then yeah, that's where the file I mentioned is, so copying the whole folder will also copy the session file.

**Comment by mikhoul** [comment] 2016-04-11 21:04
Same thing here just installed the latest beta this morning and everything seemed fine... BUT

Few minutes ago I needed to change Tab Group so I opened TG interface to find only one group ???  

On the new option for the interface, so I tried few other things but nothing changed  it was a mess after reinstalling the previous version I had Zillion of group tabs on my screen in fact one for each tabs. http://i.imgur.com/8KbHeeQ.png

So I saved my but with backup from <ins>Session Manager</ins> but something is wrong, will wait before installing the latest again. 

Regards  :blush:

**Comment by iShyboy** [comment] 2016-04-11 21:10
Right, that was with happened with me, I had 253 tabs in six or seven groups, after installing 2b3 it become 253 different groups. I saved my butt with Session Manager too, since it save every 5 minutes.

**Comment by Quicksaver** [comment] 2016-04-12 08:45
So whoever has backups in place, I hope I can ask you for some testing, since I can update from 1.0.2 to the latest beta just fine.

Immediately after updating, but before entering groups mode, open the browser console (Ctrl+Shift+J) and clear it. If it doesn't open your groups correctly, does anything appear in the console?

To clarify, getting a group per tab usually means something went wrong the time **before**, and your groups information wasn't properly saved then.

**Comment by mikhoul** [comment] 2016-04-12 17:39
@Quicksaver   I just opened a new profile to test it and here's the Log what happen when I load TG is at 13:25 Time Stamped:   http://i.imgur.com/GHhReV5.png

Screenshot of TG: http://i.imgur.com/mdIxWPK.png Just one group for now that I can see.

Going out of TG and reentered again give this in the console: http://i.imgur.com/w2YVxcI.png

And in TG in show me the 3 groups but only the main group have something inside the 2 other groups should have tabs inside but are empty: http://i.imgur.com/EqA0VnV.png

After I reinstalled the TG V2b2 here's what I see in TG: All tabs are back but inside there own groups and the 2 original group are there but empty (No message in the console): http://i.imgur.com/gMPrvO6.png

If you need more information just ask me :blush:

**Comment by Quicksaver** [comment] 2016-04-12 17:47
@mikhoul thanks for the detailed report! That is almost definitely the same as what @DuckOfDuckness reported in https://github.com/Quicksaver/Tab-Groups/issues/13#issuecomment-207948643, or at least it has the same root cause even though it's not exactly the same symptom. I've already fixed it with https://github.com/Quicksaver/Tab-Groups/commit/de5921ce78e37f19a16dcf199aad7830f8338fb6. I will upload a new beta in a few days, I hope I can ask you to try it out when I do.

**Comment by mikhoul** [comment] 2016-04-12 21:44
No problem it will be a pleasure, maybe you can put a warning on Beta3 in meantime to prevent users  :blush:

**Comment by Quicksaver** [comment] 2016-04-13 18:23
There should be no more problems updating to [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4). Please let me know if you run into any issues at all, like needing to restart the browser before being able to see your groups, having all your tabs merged into a single group, or the opposite and having each tab in its own group, etc...

**Comment by mikhoul** [comment] 2016-04-14 21:34
Everything seem to be fine on my side with latest beta 2b4 !  :smile:

Thanks !

**Comment by Quicksaver** [comment] 2016-05-13 13:04
Well since I've had no complaints about this since 2b4, I assume it's updating correctly now. Please let me know if any of this happens again.

**Closed by Quicksaver** 2016-05-13 13:04 UTC
Labels: bug, critical

**Comment by psamim** [comment] 2017-03-19 20:16
It may be useful for someone like me as I did not know it myself.
You can restore prevous sessions using _Tab Groups_ itself. Just go to _Tab Groups Options_, then _Backup / Restore_ then _Load Groups and Tabs From..._.

**Comment by lasers** [comment] 2018-01-01 20:11
Not wanting to open a new issue...

>It may be useful for someone like me as I did not know it myself.
You can restore previous sessions using Tab Groups itself. Just go to Tab Groups Options, then Backup / Restore then Load Groups and Tabs From....

I discovered this just now too. I want to merge all tabs in all (crashed, old, etc) sessions into current session.... What I can't tell is if this will stack on... because things in the list changes repeatedly / dramatically every time I load a file.

I plan on removing the old sessions after merging them... Do I go ahead and load all files from the list... and proceed... or should I load (then) proceed with each file? I just wanted to clear up this small question / confusion. Thanks! 👍 

EDIT: You have to do them one at a time.
