### ISSUE TITLE
Pull down menu wont switch groups

### ISSUE THREAD

**Issue by teyasio** [Quicksaver/Tab-Groups#329] opened 2016-06-12 19:04 UTC
Using firefox 47
After switching a few times the tabs don't change.  I have 3 groups and the only reliable way is to go into manage my groups then pick the group I want.

**Comment by Quicksaver** [comment] 2016-06-12 20:13
Does that happen if you disable all your other add-ons except for Tab Groups?

**Comment by teyasio** [comment] 2016-06-12 20:45
Did some testing looks like NoScript 2.9.0.11 is causing the issue.

**Comment by Kinematics** [comment] 2016-06-15 22:54
Duplicate of #233 then.  However the electrolysis bit is also relevant.  Re-testing, the bug only occurs when electrolysis is active.  If electrolysis is turned off, NoScript doesn't interfere with Tab Groups.

**Comment by teyasio** [comment] 2016-06-16 00:46
Well hopefully its fixable

**Comment by stephen304** [comment] 2016-06-16 13:47
Same issue here. e10s and noscript (though I leave noscript disabled globally, it's only for testing).

What I've noticed is that the pull down menu will switch to a tab from another group, but the tabs in the tab bar don't switch to show the new group, instead it shows a mix of tabs from both groups.

For example: If I have g1 and g2 with g1t1 / g2g1 etc, I switch to g2 using the menu and the menu says g2, I see g2t3, the tab bar shows g1t1, g2t1, g2t3. Clicking on g1t1 will sometimes switch me back to g1 (dropdown menu will say g1).

The most reliable way I've found to quickly switch tabs is to click g2 twice in the pull down menu. This seems to fully switch groups and display only that group's tabs in the tab bar. Only clicking it once seems to only half switch groups.

**Comment by bjesus** [comment] 2016-08-04 10:29
I'm having the same problem and I don't have NoScript installed. I'm using e10s though.

**Comment by Quicksaver** [comment] 2016-10-11 11:25
According to #233, the latest version of NoScript apparently causes no issues. I also can't seem to reproduce it at all. Everyone please make sure it's updated and re-open this if it starts happening again.

@bjesus please also re-open if you keep having this issue. Please try disabling all your other add-ons and see if that helps at all.

**Closed by Quicksaver** 2016-10-11 11:25 UTC
Labels: bug, unconfirmed
