### ISSUE TITLE
Sometimes gets stuck in grid/panorama mode

### ISSUE THREAD

**Issue by CamJN** [Quicksaver/Tab-Groups#23] opened 2015-12-09 23:55 UTC
It's hard to reproduce, but I've gotten stuck in the tab groups grid/panorama view. Once stuck I'll click on a tab to go to that group, it'll do part of the zoom animation and then stay in the grid view. Neither the keyboard shortcut nor clicking any of the tabs works to fix it in that mode, just quitting Firefox. Not something that I ever ran into with the native impl.

Sorry I don't have more info, if I have time I might try and get it to happen when I have the browser tools open.

FF44.0a2 (2015-12-09)
Mac OSX 10.11.2 (15C50)
other extensions: adblock plus, click-to-play-per-element, keychain services integration, link location bar, regex find

**Comment by Quicksaver** [comment] 2015-12-10 00:03
In the next update I'll make it possible to open the browser console (Ctrl+Shift+J) from within the groups view. So after you update, if/when this happens again please open it and see if there are any messages about the add-on in there (if you're in doubt just send me the whole thing in a text document and I'll take a look).

This should be caused by some specific action(s), if you could figure out exactly what triggers it that would be great as well. I've personally never gotten stuck like that before.

**Comment by Quicksaver** [comment] 2015-12-11 16:42
Version 1.0.1 has just been approved, so you should be able to update now. Please see if you still have this issue with it (with all the changes in it, there's always a chance it's also been fixed by some other patch), and if you do, try what I mentioned above.

**Comment by Aetf** [comment] 2015-12-11 19:43
I ran into the exact same problem right after the update to 1.0.1. However, when I disabled other add-ons and tried to find out if it is caused by a conflict, I can't reproduce it then.

**Comment by Quicksaver** [comment] 2015-12-11 20:15
I wonder if it failed to (de)initialize properly somehow... Hopefully this was a one time thing. But if it ever happens again, please try checking the console as well when it gets stuck, to see if it has any clues into what's failing.

**Comment by iShyboy** [comment] 2015-12-11 22:19
The animations could be optional though.

**Comment by Quicksaver** [comment] 2015-12-11 22:21
If you mean the zoom animations, they are, check the add-on's preferences. Are there any others?

**Comment by iShyboy** [comment] 2015-12-12 00:06
I did have the problem 2 times today, and just on the zoom, but it's OK after i disabled it.

**Comment by Quicksaver** [comment] 2015-12-12 08:34
So it doesn't happen without zoom?

**Comment by Quicksaver** [comment] 2016-03-22 19:27
I have fully removed the zoom animation in [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1) because it didn't work anymore with the several rewrites put into it. So this shouldn't happen anymore.

**Closed by Quicksaver** 2016-03-22 19:27 UTC
Labels: bug, important
