### ISSUE TITLE
Different UI design

### ISSUE THREAD

**Issue by do-bo** [Quicksaver/Tab-Groups#46] opened 2016-01-09 00:01 UTC
Hi,

First of all, thank you so much for making this addon, it's a really crucial functionality for me.

I've read that you're thinking about enchancements to the way large groups of tabs are managed.
I'd like to pitch in a mockup at http://readyformozilla.com/panorama/.

I think it's a great way to emphasize a single group of tabs, as that allows it to take most of the screen. As it is now, large numbers of groups get cramped together and make visually picking out single tabs difficult.
It could also allow to better utilize widescreen monitors (if the groups bar was vertical).

I know it's a long shot, but I found that mockup very interesting. 

Thanks again for the addon!

**Comment by Quicksaver** [comment] 2016-01-09 10:41
That's not what I was thinking about, but it's definitely interesting!

**Comment by tengwar** [comment] 2016-01-13 17:47
This is actually quite clever. Tab management is similar to window management and tab groups are like virtual desktops. This could be a redesign of this addon or another addon operating on the same data.

**Comment by do-bo** [comment] 2016-01-15 07:10
This is what I thought, especially with a very similarly working virtual desktop manager available in Windows 10.

**Comment by Eeems** [comment] 2016-01-18 21:08
+1

**Comment by KuoE0** [comment] 2016-01-19 09:36
I love this UI!! I think it will be better to organize tabs.

**Comment by Schoewilliam** [comment] 2016-01-19 15:38
Wow. That looks amazing. You should definitely consider going that way.

**Comment by WolfganP** [comment] 2016-01-19 16:31
@do-bo nice work, it seems like a wonderful improvement for the multitab/multigroup heavy user.

**Comment by do-bo** [comment] 2016-01-19 17:47
@WolfganP This is not my creation nor idea, the author created that website to attract Mozilla's interest when he applied for job :) I found that site around the time when Firefox team first planned to remove Panorama back in 2013. Interestingly, despite hiring Philipp, they never used his idea. 

It's a pity that Mozilla never really cared to make Panorama discoverable for users. It reminds me of the plan to remove full themes - first, Mozilla made them barely visible on the addon page, while promoting Personas. Then they said that full themes aren't used much and should go away ;) 
All that when half of the work to make them restartless (one of advertised advantages of Personas) was already done. There even was a prototype extension providing that functionality.

By the way, @Quicksaver's extension is regarded as <i>the</i> replacement for Tab Groups by Mozilla
https://support.mozilla.org/en-US/kb/tab-groups-removal

**Comment by sabret00the** [comment] 2016-01-22 16:33
I think that tabs within the session overview (tab group view) is kind of redundant. I  don't necessarily think that the current tiled view is the best option, but tabs is definitely a step backwards.

**Comment by AdrianoCahete** [comment] 2016-01-29 03:44
If this is will be added, it should be an option. TabMix use double click to close tabs, if i remeber correctly.

**Comment by sabret00the** [comment] 2016-01-29 09:04
That would be a Tab Mix Plus problem not a Tab Groups problem. 

BTW, there was some mocks from the UX Department at Mozilla a long time ago about evolving the design of tab groups. The mocks nor user interaction never came to fruition, but they're certainly worth reconsidering. 

On 29 Jan 2016 03:44, Adriano Caheté <notifications@github.com> wrote:

If this is will be added, it should be an option. TabMix use double click to close tabs, if i remeber correctly.

**Comment by glen-84** [comment] 2016-01-30 15:49
I like this UI, although the tab spaces need labels.

**Comment by sabret00the** [comment] 2016-02-04 12:50
Thanks to some triage on bugzilla, some of Shorlander's mocks of an evolved Tab Group/Tab Candy/Panorama experience resurfaced:
http://people.mozilla.org/~shorlander/files/australis-design-specs/images/Australis-i01-DesignSpec-MainWindow-%28Panorama%29.jpg

**Comment by ethus3h** [comment] 2016-02-08 00:01
If you're going to add any of these changes to the tab groups view, please make them optional and independent of each other, so that people can decide which parts of it they like:

* Double-click on active tab to open tab groups — I'd like this
* Double-click on inactive tabs to open tab groups — I would not like this; I want double click to switch tabs as it does now
* Large close buttons — I'd like this, but the implementation in the video takes up too much space and is messy looking since the buttons go outside of the thumbnails; I'd like to just have big close buttons in the corner of each tab that appear on hover
* Horizontal bar of tabs-of-tab-groups — I wouldn't mind this, but I'd also want to be able to organize into named tab groups within each tab of tab groups (basically, each tab would be an independent instance of the current tab groups UI)

**Comment by AdrianoCahete** [comment] 2016-02-08 05:22
> That would be a Tab Mix Plus problem not a Tab Groups problem.

Isn't correct. TabMix comes first, so it's a TabGroup problem. However, this is need to be an option.


> If you're going to add any of these changes to the tab groups view, please make them optional and independent of each other, so that people can decide which parts of it they like:

[2]

**Comment by maverick74** [comment] 2016-03-28 17:47
@Quicksaver 
I don't intent to be disrespectful here (so i truly hope you don't take me bad), but i really (and i mean really, really!!!) think the approach mentioned by do-bo (on his orignal comment) is far far better that the actual one implemented in the current v2b1 (and also better than the mockups from mozilla).

It's intuitive!!! People will feel right at home and know how to work whit it...

so i would like to ask you to, please, consider it!!! ;)

**Comment by Quicksaver** [comment] 2016-03-30 10:43
@maverick74 who said I wasn't still planning to add it? ;)

**Comment by maverick74** [comment] 2016-03-31 09:01
:D
GREAT!!! 

The "Groups-Like-Tabs" idea is just awesome!!! :D

Will follow betas closely :D

**Comment by iShyboy** [comment] 2016-03-31 11:50
If by group like tabs you mean something like this:

![groups](http://i.imgur.com/ZDbj7TW.png)
I'm on it.
It doesn't  need to be like this but you know what I mean. Paint didn't help that much too.

**Comment by Quicksaver** [comment] 2016-04-09 17:03
Here we go, help me test it out: [beta version 2b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b3).

The new single view should be fully functional. I don't think I can implement the double-click on tabs thing though; it's just very messy because each individual click still goes through, so you can end up closing not one but two tabs by accident even for example.

Tab Mix Plus prevents situations like those by implementing a rather complex set of click handlers, I really don't want to add to that by implementing my own here, that would be inviting trouble with all sorts of incompatibilities.

**Comment by iShyboy** [comment] 2016-04-10 11:47
@Quicksaver good, if we had only the name of the groups on the top, we'll have a more clean view.

**Comment by do-bo** [comment] 2016-04-10 17:29
Wow, this is amazing! I didn't expect this idea to take off like that, thank you :) 
It's a very complete beta and everything seems to work well. It's also nice to have all the different display options available.
One suggestion from me would be to put close buttons on group tiles also in the Single view mode and maybe add some right-click functionality to groups/tiles/tabs.

**Comment by Quicksaver** [comment] 2016-04-10 17:34
> put close buttons on group tiles also in the Single view mode

I have thought about that as well. I will be redesigning the close buttons as part of #50, so I will probably do that when I do that; what an awesome sentence, I know. ;)

 > add some right-click functionality to groups/tiles/tabs

At least for tabs, I already plan to make it show the same context menu as when right-clicking a tab (an actual tab). For groups, I don't see all that much that a context menu could do, there aren't those many things you can do on a group through a menu, other than close it or rename it.

**Comment by maverick74** [comment] 2016-04-11 11:57
WOW.

Amazing. Will test ASAP. 

(+1 in the Close button on group tabs - That was the thing i immediately missed (about one minute of using...)

Bugs: After installing TabGroups, i had to restart firefox in order to be able to enter groups view.

**Comment by Quicksaver** [comment] 2016-04-11 13:35
Hmm, am I missing something? I thought @do-bo meant adding a close button on the groups selector at the top on each group. There is still a close button on each group in the usual place next to the title, isn't it there one for you @maverick74 ?

**Comment by Quicksaver** [comment] 2016-04-11 13:37
> Bugs: After installing TabGroups, i had to restart firefox in order to be able to enter groups view.

This is the first I heard of something like this. Did anyone else experience a similar issue when updating to one of the betas?

**Comment by maverick74** [comment] 2016-04-11 16:51
@Quicksaver i meant something like (look where the mouse cursor is):
![screenshot_20160411_173433](https://cloud.githubusercontent.com/assets/14912461/14434902/332851a4-000d-11e6-9af4-c388df7f8180.png)

beside having to restart (on windows, and migrating from v1.0.2 to v2b3) on Linux i lost tabs - but maybe it's some conflict with session manager. On linux, however, i did not had to restart - but here i had v2b2.

**Comment by iShyboy** [comment] 2016-04-11 17:25
I always have to restart after installed a update of Tab Groups, but nevermind that.

@Quicksaver you closed #56 with the option to hide thumbs and show list mode.
But the hide thumbs its kinda dumb in the single view

![singleview](http://i.imgur.com/JVp8Isr.png)
Option to hide thumbs from the topgroups bar, and show only the names (with a separator between groups) would become more cool
![cool](http://i.imgur.com/4wzhcQ0.png)

**Comment by do-bo** [comment] 2016-04-12 22:04
> For groups, I don't see all that much that a context menu could do
That's true, one useful thing that I can think of is saving all tabs in a group to Bookmarks. This functionality is already present in Firefox, "Bookmark All Tabs" saves only tabs from the active group.

I like the idea of being able to display only group names instead of thumbnails as suggested by @iShyboy. Thumbnails aren't always a good representation for a group (e.g. the last selected tabs in two different groups are the same webpage) and naming them allows for better organization.

**Comment by Quicksaver** [comment] 2016-04-12 22:06
> That's true, one useful thing that I can think of is saving all tabs in a group to Bookmarks. This functionality is already present in Firefox, "Bookmark All Tabs" saves only tabs from the active group.

#123.

**Comment by Quicksaver** [comment] 2016-04-13 18:09
Added an option to hide the group thumbnails in [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4). I will still move the close group button up there in a later beta.

Also, there shouldn't be any more trouble in updating from an older version, but if you do run into any major problems updating (like needing to restart before being able to enter groups view, or losing groups, or seeing all tabs merged into a single group, or things like that), please let me know in #178.

**Comment by iShyboy** [comment] 2016-04-13 18:16
So far no problems with the new beta.
Just waiting to see the groups in the topbar of single view with just the names and not blank space as in the [concept](https://github.com/Quicksaver/Tab-Groups/issues/46#issuecomment-208461422), in a later beta.

**Comment by Quicksaver** [comment] 2016-04-13 18:19
@iShyboy that's what I meant with "Added an option to hide the group thumbnails". Check the add-on preferences. ;)

**Comment by iShyboy** [comment] 2016-04-13 18:22
Just saw it @Quicksaver for some reason, the tabview opened like normal, but about:tabgroups not, I had to restart, so I didn't saw it before, but thats awesome. Thanks.

**Comment by Quicksaver** [comment] 2016-04-13 18:24
That's weird. Never ran into an issue like that, the preferences tab is supposed to be closed when the add-on is disabled (thus when updating), so it's not like you'd even need to refresh it, let alone restart the browser. Please let me know if you notice something like this again.

**Comment by iShyboy** [comment] 2016-04-13 18:27
@Quicksaver That's why I didn't mention it on #178, I'm still with FF 42.

**Comment by Quicksaver** [comment] 2016-04-13 18:30
Oh that's right, I believe you mentioned that before, haven't you? You're bound to run into problems when running older versions of Firefox, I really can't support anything older than 45 (but I will support that during its ESR run, which will be the better part of a year). I hope you're able to update soon.

**Comment by iShyboy** [comment] 2016-04-13 18:34
@Quicksaver most of my tests I run on the updated version, just I can't leave Redirector with my main profile. It doesn't work with ff 44+ on about:pages.

**Comment by maverick74** [comment] 2016-04-14 21:24
@Quicksaver: I'm not having any issue either!

And i have to say i loved the option to hide the thumbnails on groups!!! Great move! Will be waiting for the close buttons for later, then... :)

Also... here's another idea: Instead of a bottom scrollbar would it be possible to have, for groups, a Right / Left arrow, just like we have for tabs, when they don't fit horizontally???

(this, of course, would have to pass on other users opinion on the subject.)

**Comment by Quicksaver** [comment] 2016-04-14 21:28
> Also... here's another idea: Instead of a bottom scrollbar would it be possible to have, for groups, a Right / Left arrow, just like we have for tabs, when they don't fit horizontally???

I did consider that. I chose to go with the scrollbar for now because it's a floating one so it's much more space saving. And quite frankly it's much easier to do. :stuck_out_tongue_winking_eye: I think I'll leave it for now at least, but if there's a strong pull to that idea I'll of course reconsider.

**Comment by iShyboy** [comment] 2016-04-14 21:31
You could put the arrows in the groupbar of single view @Quicksaver as in the tabs, it'll not take that much of space anyway. and instead of the usual scroll, it would be better scroll per group.

**Comment by ttonyh** [comment] 2016-05-08 19:36
Great work so far, I love what you did with the new layout options; I just tried out v2b5 and I'm quite impressed. One thing I'd like to add is that, although the new layouts seem very useful, I still tend to prefer the Free Arrange layout. I like the ability to position groups in predictable regions of the screen.

The major problem with the Free Arrange layout, is still (since original release) is the unexpected behavior of the tab groups after moving or resizing. Resizing or moving any group that is adjacent to others, could cause a grid like layout to shift dramatically and unpredictably; sometimes knocking the entire layout out of order.

Here are some suggestions to making the Free Arrange a more manageable / usable layout:

1) Moving or resizing of adjacent groups DON’T cause others near-by to move / bump / resize. Also, allowing groups to overlap - which isn’t necessarily a bad thing.

2) Increase the auto-align feature to a higher pixel threshold. That way, when you try to align a group to others, you have a better chance getting sides level to others.

3) Allow for resizing of a group from all sides and corners. This will increase the speed and precision for a perfect grid alignment, if that’s your goal.

4) In group scroll view, use the same type of layout as implemented in the new Grid display. I think that works better than a list


Other possible UI improvements:

1) Reduce the rounded corners; the new Grid display looks more modern in comparison.

2) Reduce or remove the drop shadow. They just creates more visual clutter and look a little dated.

3) Allow for groups to be positioned off screen. That would give a larger work area that’s not limited by the window size. A keyboard shortcut / modifier can be added that toggles from regular window scroll to tab group scroll. Maybe even a “pan” view, so you can pan the screen of all your groups, like in Photoshop, after zooming into a large photo.

**Comment by Quicksaver** [comment] 2016-05-08 21:06
@ttonyh all that really should have been in its own issue. It's a lot worth discussing but has nothing to do with single view (which is what this thread is about). I created #201 and I will reply to you there.

**Comment by Quicksaver** [comment] 2016-05-13 12:35
And with the close button in the groups selector and a few other tweaks and fixes, I think we're done here. Please give [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) a try and let me know if you have any problems with it.

**Closed by Quicksaver** 2016-05-13 12:35 UTC
Labels: enhancement
