### ISSUE TITLE
"Move to Group (in Background)" feature request

### ISSUE THREAD

**Issue by mdh0312** [Quicksaver/Tab-Groups#371] opened 2016-07-17 20:12 UTC
Would allow saving a tab to a group without switching focus from current group. 

![move to group in background](https://cloud.githubusercontent.com/assets/20505314/16902839/dee69376-4c1f-11e6-8019-375e049edb86.png)

**Comment by leggewie** [comment] 2016-07-18 14:45
This is the current default behaviour for me.  And I think that's the way it should be.  If we need to have a choice then please don't clutter the context menu but make it a configuration (IOW, the user can only have it one or the other but not choose at the time of moving the tab). KISS.

**Comment by PrototypeNM1** [comment] 2016-08-05 01:48
This is a really useful feature in practice, and is implemented in the Tab Groups Button extension.

**Comment by Quicksaver** [comment] 2016-10-11 19:35
The Move To Group action is supposed to happen in the background already, as in it shouldn't switch groups at all. This seems like a duplicate of #268. Please let me know if that's not happening for you.

**Closed by Quicksaver** 2016-10-11 19:35 UTC
Labels: duplicate
