### ISSUE TITLE
A tab travels from its group to the main tab group

### ISSUE THREAD

**Issue by GrayFace** [Quicksaver/Tab-Groups#149] opened 2016-03-20 08:32 UTC
Started since Tab Groups became an extension. There's one group (called Filter) in which I only have 1 tab. On startup that tab frequently moves to the group I mostly use, called Main. I'm not sure, but think I experienced something similar when Tab Groups were a part of the browser, but recreating groups fixed that.
Here's a screenshot of my groups: https://dl.dropboxusercontent.com/u/44735333/tmp/TabGroupsBug.png

**Comment by Quicksaver** [comment] 2016-03-20 09:55
Do you use [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/)? If so, this may be #118.

**Comment by GrayFace** [comment] 2016-03-21 07:09
Yes I do. Also, FF almost never closes without a crash, so it always starts with Session Manager's restore session dialog.

**Comment by Quicksaver** [comment] 2016-03-21 10:11
I'm closing this as a duplicate of #118 then, hopefully when I look into it, this will also be fixed. If by the next version you still experience this, please let me know.

Also, if you have constant crashes, you may want to figure out the cause, as it's very likely that is the cause for your specific case (regardless of Session Manager). Crashes can easily lead to corrupted session data, which in your case means losing the groups information about that one group. Try disabling your add-ons, starting a new session, making a clean profile, etc, and see if you can get the crashes to stop. Firefox really shouldn't crash that often.

**Closed** 2016-03-21 10:11 UTC
Labels: duplicate
