### ISSUE TITLE
New 'Tiled Icons' option (v2.1b3) doesn't work well with unloaded tabs

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#439] opened 2016-10-17 09:13 UTC
#### Screen Below
![2016-10-17_badicons_tabgroups2 1b3](https://cloud.githubusercontent.com/assets/364460/19431671/63c15fbe-9427-11e6-97ff-5812c6dfe096.png)
Look to towards the right edge and you will see that the singular loaded tab is the only one that displays it's icon properly. TG has clearly acquired icons for the inactive/unloaded tabs, they're there alright, just all nudged out of the boxed framework.

I assume they're incorrectly being treated as thumbnails still?!?

**Comment by Quicksaver** [comment] 2016-10-17 09:17
Already fixed locally actually. Will upload a new beta soon.

**Comment by Quicksaver** [comment] 2016-10-17 16:22
Should be fixed in [beta version 2.1b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b4). Please try it out and let me know how it works for you.

**Closed by Quicksaver** 2016-10-17 16:22 UTC
Labels: bug

**Comment by jmain33** [comment] 2016-10-19 06:50
#### Would using the *badge style icon* (as seen in the above screenshot) from beta3 be problematic?
Also, the **close [X] symbols** are too large; to be particular they're overly protrusive/noticeable. Maybe the icons shouldn't have an **[X]**, or better yet they could only show them on hover; speaking of which they, the **[X]**'s, aren't obvious enough when being hovered. They should turn red similar to the close buttons on the actual Firefox tabs. This could also be applied to thumbnails view, etc.

**Comment by Quicksaver** [comment] 2016-10-19 08:59
> Would using the badge style icon (as seen in the above screenshot) from beta3 be problematic?

I don't understand what you mean by this. You can disable this behavior if that's what you mean, either through each individual group's options or globally in the add-ons options (don't forget to apply to all groups).

> Maybe the icons shouldn't have an [X], or better yet they could only show them on hover

This would make them inaccessible on touch screens.

> They should turn red similar to the close buttons on the actual Firefox tabs.

This only happens in windows vista and 7 I believe. I don't believe it's worth it creating new icons just for those at this point.

**Comment by jmain33** [comment] 2016-10-19 09:57
By **Badge Style Icon**, I was referring to the colored-in box that surrounded the icons in beta3. Beta4 got rid of that and just shows the bare icon. What I meant to convey was that I preferred the icons with that color-matched box around them. I'm just curious as to your intent/purpose for removing that detail.

The previous comment is just a minor note of things I find _slightly off_ concerning the graphic layout. Though the solutions I concocted aren't appropriate for you to use, I stand by my initial observances.

**Comment by Quicksaver** [comment] 2016-10-19 10:31
It's supposed to show the "unloaded" color around the icon as well, just as it does for the tab thumbnails. Note in the screenshot the difference between the unloaded and loaded facebook tabs:
<img width="188" alt="2016-10-19_11-28-21" src="https://cloud.githubusercontent.com/assets/802086/19515432/4d1f0684-95ef-11e6-8b41-5865f7c39eff.png">
Is this not happening for you? Note that in your case it may be difficult to notice, as you've chosen a color that's very similar to the group's background color.

**Comment by jmain33** [comment] 2016-10-19 11:11
It's OK in that regard :-) The borders/text are colored fine. With v2.1b4 the **inner-gradient** is what I'm not seeing (e.g. from your screen, the red shading around the G+ icon or the light blue around twitters bird). All I see is the icons and their borders, in-between is transparent -> showing the 'Tab Groups' background color.
![2016-10-19_065337](https://cloud.githubusercontent.com/assets/364460/19516287/4bf2557a-95c9-11e6-8f0a-f17d4ee1f3ef.png)
Also note, from my current screenshot, that one of my icons has disappeared. It was there previously, I saw when TG first generated it; as the URL loaded while I was in a previous Group Manager session. In all later entries to Group Manager I haven't seen that tabs icon. The icon is present when I view that tab on the tab-bar and other tabs from that same site are currently showing their icons in Group Manager.

**Comment by Quicksaver** [comment] 2016-10-19 11:18
> the inner-gradient is what I'm not seeing

I wonder if it's something I messed up for the Windows 7 style. I'll check it out. Could you please open a new issue about this and in the meantime, test something for me. Restart Firefox, open the browser console (Ctrl+Shift+J) and clear it. Now enter groups view for the first time (try not to do anything else for a minute or two) and see if anything appears in the console in that time.

> one of my icons has disappeared

Yeah, that happens some times, I'm still trying to figure out exactly why/when. It's... an elusive bug... Could you also open a new issue about it so that I can let you know when I fix it? Steps to faithfully reproduce this would be awesome, by the way. :)

**Comment by jmain33** [comment] 2016-10-19 12:42
Here's what spat out…
![2016-10-19_082640](https://cloud.githubusercontent.com/assets/364460/19518702/83948fe0-95d6-11e6-89bd-e893dd2ea202.png)
Doesn't look good :confused: 
***
BTW, after restarting, group manager kept displaying my stacked tabs in an aspect ratio of 212:218 (*first this has ever happened TMK*), though it self-corrected back to 355:224 eventually. My monitor's AR is 16:10 so the second value is right-on.

**Comment by Quicksaver** [comment] 2016-10-19 19:41
[Beta version 2.1b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b6) should fix both issues. Please let me know if you still have any problems with it, but in new issues as none of those were related to TMP at all. ;)

**Comment by jmain33** [comment] 2016-10-19 20:28
Nothing in this issue ever had anything to do with TMP¿ :confused: ?
I never mentioned that add-on here.  
I know you're quite busy :wink: though.

**Comment by Quicksaver** [comment] 2016-10-19 20:58
> Nothing in this issue ever had anything to do with TMP

The unloaded tabs status comes from Tab Mix Plus, colors too. ;)

**Comment by jmain33** [comment] 2016-10-21 21:05
`Win7 Pro 64-bit`, `Core i7 960 @3.20 GHz`, `24 GB RAM`, `Firefox 47.0.1`, `Tab Groups 2.1b6`
> @Quicksaver, Please let me know if you still have any problems with it, but in new issues as none of those were related to TMP at all. ;)

  - The icons' <ins>gradient filling</ins> loads incredibly slowly, ≈a couple minutes for a couple dozen.  
***specs lised above***  

I'm still posting updates here because it all seems relevant to me (i.e. *everything so far has had to do with the newly introduced tiled icons*); I changed the title to reflect TMP's involvement, if that's what you were hinting at. :wink: I didn't know/realize it was TMP's fault, since the colors defined by that add-on were always displayed properly by TG.

**Comment by Quicksaver** [comment] 2016-10-22 22:59
> The icons' gradient filling loads incredibly slowly, ≈a couple minutes for a couple dozen.

That's a non-issue. Calculating the dominant color of an image is heavy work, even for small images like page icons. This is all done sequentially and in an asynchronous way (and where possible off the main thread), so that the window doesn't lock at all while this happens. That means it will take a bit longer, especially if the browser is still working on something else in the background. But it's a necessary compromise to put off these calculations until it can actually use that processing power freely.

> I'm still posting updates here because it all seems relevant to me (i.e. everything so far has had to do with the newly introduced tiled icons)

It's not, only your first comment was. I think you're confusing things, the tiled icons have nothing to do with TMP at all. If you disable TMP, you'll still see the tiled icons, you just won't see the unloaded colors around them for unloaded tabs. Only the first comment was related to TMP, because it was the unloaded tabs (and hence the script that was inserting the unloaded colors around the icons) that was screwing things up.
