### ISSUE TITLE
Data Storage Location>? 

### ISSUE THREAD

**Issue by meru448** [Quicksaver/Tab-Groups#225] opened 2016-05-27 07:05 UTC
I've recently opted to "refresh" firefox & ported over sessionmanager, which has been working in-tandem with Tab Groups quite well.

I can't seem to find the location where Tab Groups stores/remembers the groups, as it stands now when I load a session that I /know/ had groups it now loads strictly into one group. 

Thank you for your time.

**Comment by Quicksaver** [comment] 2016-05-27 08:32
How are you loading that session? The groups are stored in the session itself, so they should be there. Session Manager should also be perfectly compatible with Tab Groups.

**Comment by meru448** [comment] 2016-05-27 09:42
So I suppose it was working the whole time, just a display error of sorts that I needed to investigate further. 

From the top:

I refreshed Firefox, re-installed Session Manager & Tab Groups. Transferred over my old sessions folder, loaded up a session that I knew had Tab Groups.

upon loading right clicking & selecting "move to group" ( which typically prompted a brief "freeze" & the listing of the group(s) )) I was instead greeted with only "New Group" & it had visually appeared that all the tabs were now just in one group, however upon clicking the Tab Groups button the Groups appeared & the appropriate tabs were in them. 

An odd interaction to be sure, but I believe this resolves my issue. 

Thank you for your time & continuing the Tab Groups in Firefox, I honestly don't know how people browse w/o Tab Groups.

**Comment by Quicksaver** [comment] 2016-05-27 09:54
> upon loading right clicking & selecting "move to group" ( which typically prompted a brief "freeze" & the listing of the group(s) )) I was instead greeted with only "New Group" & it had visually appeared that all the tabs were now just in one group

That's odd, it sounds like it's not fully initializing when it shows the "Move to group" sub menu. If you still have the Session Manager backups, could you please try refreshing everything in the same way, but instead of installing Tab Groups from the AMO website, try it with the latest [beta version 2b10](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b10) and see if that still happens.

That really shouldn't matter regardless of the version of Tab Groups you have, but since I can't seem to reproduce it with that beta, maybe it's something that's been fixed by one of the many rewrites that's been done. By the way, you'll notice that there's a lot of changes in that beta from the latest release, so it's definitely worth it giving the "How to use" page in the add-on preferences a read, to get acquainted with the new features.

**Comment by meru448** [comment] 2016-05-27 21:51
The beta does indeed seem to resolve that issue, the new features are also quite neat.

Thank you again.

**Comment by Quicksaver** [comment] 2016-05-27 21:51
I'm glad to hear that, please let me know if it ever happens again.

**Closed by Quicksaver** 2016-05-27 21:51 UTC
Labels: bug, unconfirmed
