### ISSUE TITLE
Switch to next/previous group not working

### ISSUE THREAD

**Issue by truncsphere** [Quicksaver/Tab-Groups#75] opened 2016-01-28 03:46 UTC
For about 3 weeks now the shortcuts to switch to next or previous groups are no longer working. 
I changed the shortcut to various other combinations and am having no luck. 
However, enter/exit group mode does work.

**Comment by Quicksaver** [comment] 2016-01-28 10:06
Do they work if you disable all your other add-ons except for Tab Groups? When you use those shortcuts and they don't work, does anything appear in the browser console (Ctrl+Shift+J)?

**Comment by shosuroyokaze** [comment] 2016-01-28 14:29
I'm having a similar problem. It seems that using ` as the key for anything prevents it from working. It's a minor problem as I can switch to a different key but I've always the tilde.

**Comment by Quicksaver** [comment] 2016-01-28 14:31
#65

**Comment by shosuroyokaze** [comment] 2016-01-28 14:35
I have a US English keyboard so the problem isn't that I need to hit shift to make the `.

**Comment by Quicksaver** [comment] 2016-01-28 14:37
That's why I marked it as a duplicate.

**Comment by truncsphere** [comment] 2016-01-28 14:40
Disabled all add-ons except TMP and Tab Groups and it is still not working. I attached what is shown on the console after the key press. 
![tb1](https://cloud.githubusercontent.com/assets/16292618/12647378/b746e310-c589-11e5-8530-182876b320b6.JPG)

I have another PC with all the same extensions synced and have the same issue. Oddly, I disabled all the same add-ons and group switching worked. Enabled one by one and it still works.

**Comment by Quicksaver** [comment] 2016-01-28 14:41
I was about to ask for some debugging info in that other thread, thanks for that! I'll have to take a look.

**Comment by cmcqueen** [comment] 2016-01-29 00:16
The Ctrl-` and Ctrl-Shift-` keyboard shortcuts aren't working for me on a standard US keyboard. In the browser console, I get the same message as truncsphere did.

I have the following extensions:

* Character Identifier
* Easy Copy
* Show Anchors 2
* Tab Groups
* uBlock Origin

**Comment by Quicksaver** [comment] 2016-01-31 11:05
> Disabled all add-ons except TMP and Tab Groups and it is still not working.

Does it work if you disable TMP?

**Comment by cmcqueen** [comment] 2016-01-31 22:54
I think I've figured out a cause of this issue: If there is an empty tab group (i.e. on the tab groups view, there is an empty box), then the keyboard shortcuts don't work. If all tab groups contain at least one tab, then the keyboard shortcuts work fine.

**Comment by cmcqueen** [comment] 2016-02-03 03:35
However, despite my previous findings, Shift-Ctrl-\` is still not working for going to previous tab group.

**Comment by truncsphere** [comment] 2016-02-03 14:06
Not sure how/when Tab Groups was re-enabled, but `Ctrl` + ``` appears to be working correctly now. I have only tested this on one of the 2 PC's and still need to check the other.

**Comment by jordila** [comment] 2016-02-06 10:27
Same for me here ... tried diferent shortcuts for next/prev tab groups switching without success.

**Comment by Quicksaver** [comment] 2016-02-06 16:22
Testing time, how many of you can use the shortcuts with [beta version 1.0.3b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.3b3)? If not, can you use the shortcuts depending on what character/key you choose for it in the preferences or not at all?

Note that beta is not signed, so you'll have to disable preference "xpinstall.signatures.required" in about:config in order to install it.

**Comment by MailYouLater** [comment] 2016-02-29 22:39
Hi,
     I just installed Tab Group, and was unable to use the Ctrl+`/Ctrl+Shift+` default keyboard shortcuts, but was able to use others if I chose to change them in the Options. FYI, I'm using Firefox 44.0.2 on Windows 10 (Version 1511), and I launched it straight to a Private Browsing window (via the option in the Jumplist, as I have Firefox pinned to the taskbar), then (after some other browsing) I installed Tab Group 1.0.2 (current offering from AMO), and noticed that this feature didn't work unless I changed the keyboard shortcuts. Also, if I put them back to the defaults it went back to not working.
Next, I exited Firefox, and relaunched it again (again straight into Private Browsing via the Jumplist option), and Ctrl+` worked, but Ctrl+Shift+` did not.
I have since changed the second shortcut to Ctrl+Shift+~ (as I have en_US keyboard layout), and it seems to be working as expected, but I thought this information might be useful to you and/or some of your users.

Thank you.

**Comment by MailYouLater** [comment] 2016-02-29 23:08
I can also verify that (once I got the shortcuts working), the shortcuts stop working if I have a tab group without any tabs in it. (Note: It is only possible to create such a tab group if you have at least one pinned tab.)

**Comment by monk-time** [comment] 2016-03-08 18:11
@MailYouLater, I have the same issue with shortcuts disabling if there's an empty untitled group with a pinned tab as you and truncsphere (down to the same line number in the error message in the console), and it looks like it was taken care of in e752627. Have you tried the beta version linked above? (I haven't checked it though)

(FF45x32, Win7, TG 1.0.2)

**Comment by MailYouLater** [comment] 2016-03-18 02:01
No, I haven't yet.

I'm not sure when I'll have time to play with this kind of thing again, so hopefully someone else can check it out.

**Comment by Quicksaver** [comment] 2016-03-22 19:13
Please re-open if anyone still has this problem with the latest beta.

**Closed by Quicksaver** 2016-03-22 19:13 UTC
Labels: bug, minor

**Comment by jabjab** [comment] 2016-06-01 21:57
I just encountered this issue with the new release for previous-group switching (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>`</kbd>); switching to <kbd>Ctrl</kbd>+<kbd>~</kbd>, as suggested in in other issues, resolved the problem.

**Comment by Quicksaver** [comment] 2016-06-01 22:01
@jabjab in your keyboard, is the <kbd>`</kbd> key modified in any way if you press shift?

**Comment by jabjab** [comment] 2016-06-01 22:08
@Quicksaver Only in that it produces `~` when used for text entry. I assume the issue is due to Firefox addons (or this addon in particular) now handling key events by character rather than actual key combinations for printable keys, because it was working in previous versions of the addon (not just the built-in tab groups from before). On the other hand, it may be due to the OS in use intercepting the key events and converting before the browser actually gets to see them (using Ubuntu 15.10 right now, don't know why it would do something that would mess up conventional key event behavior so much).

**Comment by Quicksaver** [comment] 2016-06-01 22:13
Yes, if the produced character is ~, then that's what you'll have to define.

**Comment by MailYouLater** [comment] 2016-06-26 19:29
It's awfully silly that setting it as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>`</kbd> doesn't work too. :confused:

**Comment by Quicksaver** [comment] 2016-06-26 19:31
What doesn't work? Does pressing Shift+` produce a different character on your keyboard? if not, please open a new issue and describe what the problem is in more detail.

**Comment by MailYouLater** [comment] 2017-08-07 22:53
Sorry I didn't get back to you ... a long time ago.
Setting it to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>\`</kbd> doesn't work as expected, because <kbd>Shift</kbd>+<kbd>\`</kbd> makes `~`.
I was saying that it was silly that setting it to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>\`</kbd> isn't equivalent to setting it to <kbd>Ctrl</kbd>+<kbd>~</kbd> on keyboards where `~` is generated by pressing <kbd>Shift</kbd>+<kbd>\`</kbd>.
