### ISSUE TITLE
I don't have the icon at the top

### ISSUE THREAD

**Issue by pjdemmitt** [Quicksaver/Tab-Groups#230] opened 2016-05-31 04:36 UTC
I don't have the icon at the top right as you can see in the attached screenshot. I can enable TabGroups with Ctl-Shift-E, but I would like the icon. Is there a way to force it? It doesn't seem to be in the list of icons in the Customize panel either.

Thanks for  your help.

![tabgroup1](https://cloud.githubusercontent.com/assets/19660148/15663318/b5722744-26c7-11e6-8eae-22d2df64a99c.jpg)

**Comment by Quicksaver** [comment] 2016-05-31 07:35
If you can use the keyboard shortcut, then the add-on is fully initialized. The icon must be somewhere, are you sure it's not in customize mode? Have you checked in any other toolbars you may have (even hidden/disabled ones)?

**Comment by pjdemmitt** [comment] 2016-05-31 12:07
Luis,
Thank you for getting back to me. Yes, the add-on works as it should. I
have checked the icons in the Customize mode and it is not there. It is not
in any other toolbars, either. Believe me, I checked everywhere before I
contacted you and checked the forum to see if anyone else had the same
problem.
I guess I was wondering if there is a way to force it to be visible.
If not, it works fine and I will just have to use the keyboard.
Thank you again for the add-on and getting back to me.
-Paul

Paul Demmitt
9337 Angelina Circle
Columbia, MD 21045-5110

Cell & Office:  410-499-4762
____________________________

**Comment by Quicksaver** [comment] 2016-05-31 12:10
There's no way to force it to be visible, because it should already be visible.

Can you please try [beta version 2b10](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b10) and see if you can find the button anywhere with it? Note that there are extensive changes in that beta from the current release, so it is definitely worth it giving the "How to use" page in the add-on's options a read, to get acquainted with the new features.

**Comment by pjdemmitt** [comment] 2016-05-31 12:41
Luis,
Thank you again. I did install the beta version and there is still no icon.
Checked everywhere. I have no idea why it doesn't show. But I can use it
the way it is.
If, in your efforts, you figure it out, let me know. Please don't obsess
over this, especially if I seem to be the only one with the problem.
Best,

Paul

**Comment by Quicksaver** [comment] 2016-05-31 13:52
It could be a conflict with another add-on that somehow prevents the icon from appearing. Could you please try disabling all your other add-ons and themes, except for Tab Groups, and see if you can find the button anywhere then?

**Comment by pjdemmitt** [comment] 2016-06-01 02:56
Luis,

I did disable all the add-ons, in groups of 6 (I have about 14-15), and couldn’t identify any one that caused the icon’s disappearance. I will try again and see what happens.

~Paul 






Sent from Windows Mail





From: Luís Miguel
Sent: ‎Tuesday‎, ‎May‎ ‎31‎, ‎2016 ‎9‎:‎52‎ ‎AM
To: Quicksaver/Tab-Groups
Cc: Paul Demmitt, Author





It could be a conflict with another add-on that somehow prevents the icon from appearing. Could you please try disabling all your other add-ons and themes, except for Tab Groups, and see if you can find the button anywhere then?

**Comment by Quicksaver** [comment] 2016-06-01 18:59
I realized something that may not be so obvious, I should have mentioned this sooner. In version 2, the button shows the name of the current group, rather than the icon, if it's placed next to the tabs, and in a few other places. But in customize mode it should still show the icon as usual. Could you be missing it because of this?

**Comment by Quicksaver** [comment] 2016-06-01 19:17
For example, if you go to the Tab Groups preferences, and disable the preference to "Show the name of the active group" in the button, does it appear anywhere then?

**Comment by vIr-s** [comment] 2016-06-01 22:43
Facing the same issue. Unable to open to groups view. Icon is not present and keyboard shortcut doesn't work either. Disabling "Show the name of the active group" option doesn't help either.

**Comment by Quicksaver** [comment] 2016-06-01 22:53
@vlr-s if the keyboard shortcut doesn't work, that's definitely a different issue. It sounds like the add-on isn't enabled at all (which is far more serious of course). Please open a new issue and let me know there if disabling all other add-ons except for Tab Groups helps at all.

**Comment by iShyboy** [comment] 2016-06-01 23:19
This is some problem with the two options of panel and show group name.
I confirmed this just now, and the button reappeared after I clicked reset to default in the customize mode.

**Comment by JPFrancoia** [comment] 2016-06-02 14:31
Bug confirmed. @iShyboy got the solution though. restoring to defaults and unselecting the 2 options restored the icon for me, and also the previous behaviour.

**Comment by pjdemmitt** [comment] 2016-06-02 16:04
Resetting defaults in the Customize menu did it! The icon is now there.
Thanks for the solution. I did have to deselect "Show name of active group"
in the settings for Toolbar groups (first option under Toolbar Buttons
section)

**Comment by vIr-s** [comment] 2016-06-02 18:22
@Quicksaver , as mentioned in the #239 , I disabled the **cck** configuration and Tab Groups works fine. It would be nice to have Tab Groups working along with the **cck** configuration.

**Comment by czackwaltz** [comment] 2016-06-02 19:22
cross post from #267. IBM CCK 2.2.4 (updated 2015-12-22) seems to be the culprit. After I disable and restarted, I got the Tab Group icon back. If I reenabled IBM CCK 2.2.4, the Tab Group icon disappeared.

**Comment by tengwar** [comment] 2016-06-03 16:49
CCK is a different bug (#239). This is for cases without CCK installed.

I had the same issue: no button, but ctrl+shift+E worked and Tab Groups' settings page also worked. I had quick access and show name disabled. I fixed it by enabling them and then disabling them again.

**Comment by Quicksaver** [comment] 2016-10-14 23:46
Alrighty then.

If you can, please try installing [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and re-open this issue if it happens again. Also, if it does, before you try restarting Firefox, please open the browser console (Ctrl+Shift+J, Command+Shift+J on Mac) and see if there are any warnings or errors at the bottom about Tab Groups (if in doubt, just copy the whole thing here and I'll take a look).

**Closed by Quicksaver** 2016-10-14 23:46 UTC
Labels: bug, unconfirmed
